import type {
  ActivityAiAction,
  ActivityApproval,
  ActivityAttachment,
  ActivityComment,
  ActivityEntry,
  ActivityFollower,
  ActivityNote,
} from "@/lib/activity/types";

// ─── Product: prod_0001 (Lenovo ThinkPad E16 example from spec) ───────────────

const productEntries: ActivityEntry[] = [
  {
    id: "act_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "create",
    title: "Product created",
    description: "Lenovo ThinkPad E16 added to catalog",
    actor: "Admin",
    actorInitials: "AD",
    at: "2026-01-15T10:00:00Z",
  },
  {
    id: "act_p001_2",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "update",
    title: "Price updated",
    fieldChanges: [{ field: "Price", oldValue: "6500", newValue: "6200" }],
    actor: "Admin",
    actorInitials: "AD",
    at: "2026-01-18T15:30:00Z",
  },
  {
    id: "act_p001_3",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "update",
    title: "Stock updated",
    fieldChanges: [{ field: "Stock", oldValue: "12", newValue: "48" }],
    actor: "Warehouse Team",
    actorInitials: "WH",
    at: "2026-02-05T09:15:00Z",
  },
  {
    id: "act_p001_4",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "ai_action",
    title: "AI SEO generated",
    description: "Meta title, description, and FAQ schema generated by Chief AI Agent",
    actor: "AI Agent",
    actorInitials: "AI",
    at: "2026-02-10T11:00:00Z",
  },
  {
    id: "act_p001_5",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "status_change",
    title: "Status changed",
    fieldChanges: [{ field: "Status", oldValue: "Draft", newValue: "Published" }],
    actor: "Manager",
    actorInitials: "MG",
    at: "2026-02-12T14:00:00Z",
  },
  {
    id: "act_p001_6",
    entityType: "product",
    entityId: "prod_0001",
    actionType: "update",
    title: "Description updated",
    description: "Product description rewritten for clarity",
    actor: "Sadia Rahman",
    actorInitials: "SR",
    at: "2026-03-01T10:30:00Z",
  },
];

const productComments: ActivityComment[] = [
  {
    id: "cmt_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    author: "Rahim Uddin",
    authorInitials: "RU",
    body: "@Sales Team Please verify stock before publishing.",
    mentions: ["Sales Team"],
    at: "2026-02-11T16:00:00Z",
  },
  {
    id: "cmt_p001_2",
    entityType: "product",
    entityId: "prod_0001",
    author: "Sales Team",
    authorInitials: "ST",
    body: "Stock confirmed — 48 units available in Dhaka warehouse.",
    at: "2026-02-11T16:45:00Z",
  },
];

const productNotes: ActivityNote[] = [
  {
    id: "note_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    author: "Manager",
    authorInitials: "MG",
    body: "High-margin laptop — prioritize in Q1 campaigns. Margin target 22%.",
    at: "2026-02-12T13:50:00Z",
  },
];

const productAttachments: ActivityAttachment[] = [
  {
    id: "att_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    name: "thinkpad-spec-sheet.pdf",
    fileType: "pdf",
    size: "1.2 MB",
    uploadedBy: "Admin",
    at: "2026-01-15T10:05:00Z",
  },
  {
    id: "att_p001_2",
    entityType: "product",
    entityId: "prod_0001",
    name: "product-hero.jpg",
    fileType: "image",
    size: "340 KB",
    uploadedBy: "Sadia Rahman",
    at: "2026-01-20T11:00:00Z",
  },
];

const productFollowers: ActivityFollower[] = [
  { entityType: "product", entityId: "prod_0001", userId: "u1", name: "Sadia Rahman", initials: "SR" },
  { entityType: "product", entityId: "prod_0001", userId: "u2", name: "Rahim Uddin", initials: "RU" },
  { entityType: "product", entityId: "prod_0001", userId: "u3", name: "Manager", initials: "MG" },
];

const productAiActions: ActivityAiAction[] = [
  {
    id: "ai_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    action: "AI Generated Description",
    summary: "Generated 180-word product description highlighting Intel Core i7, 16GB RAM, and business-grade durability.",
    at: "2026-02-08T09:00:00Z",
  },
  {
    id: "ai_p001_2",
    entityType: "product",
    entityId: "prod_0001",
    action: "AI Generated SEO",
    summary: "Meta title, description, and FAQ schema created. SEO score improved from 62 to 89.",
    at: "2026-02-10T11:00:00Z",
  },
  {
    id: "ai_p001_3",
    entityType: "product",
    entityId: "prod_0001",
    action: "AI Suggested Price",
    summary: "Suggested price ৳6,200 based on competitor analysis (3% below market average).",
    at: "2026-01-17T14:00:00Z",
  },
];

const productApprovals: ActivityApproval[] = [
  {
    id: "appr_p001_1",
    entityType: "product",
    entityId: "prod_0001",
    status: "requested",
    requestedBy: "Sadia Rahman",
    at: "2026-02-11T10:00:00Z",
  },
  {
    id: "appr_p001_2",
    entityType: "product",
    entityId: "prod_0001",
    status: "approved",
    requestedBy: "Sadia Rahman",
    actedBy: "Manager",
    reason: "Stock verified, pricing approved",
    at: "2026-02-12T14:00:00Z",
  },
];

// ─── Order: ord_1001 ─────────────────────────────────────────────────────────

const orderEntries: ActivityEntry[] = [
  { id: "act_o001_1", entityType: "order", entityId: "ord_1001", actionType: "create", title: "Order created", actor: "System", actorInitials: "SY", at: "2026-06-08T08:00:00Z" },
  { id: "act_o001_2", entityType: "order", entityId: "ord_1001", actionType: "update", title: "Payment received", description: "bKash payment confirmed — ৳12,500", actor: "Payment Gateway", actorInitials: "PG", at: "2026-06-08T08:05:00Z" },
  { id: "act_o001_3", entityType: "order", entityId: "ord_1001", actionType: "assignment", title: "Assigned to warehouse", description: "Assigned to Sadia Rahman", actor: "Manager", actorInitials: "MG", at: "2026-06-08T09:00:00Z" },
  { id: "act_o001_4", entityType: "order", entityId: "ord_1001", actionType: "status_change", title: "Status changed", fieldChanges: [{ field: "Status", oldValue: "Processing", newValue: "Packed" }], actor: "Sadia Rahman", actorInitials: "SR", at: "2026-06-09T10:00:00Z" },
  { id: "act_o001_5", entityType: "order", entityId: "ord_1001", actionType: "status_change", title: "Shipped", fieldChanges: [{ field: "Shipment", oldValue: "Packed", newValue: "Shipped" }], description: "Pathao — tracking PTH-88291", actor: "Warehouse Team", actorInitials: "WH", at: "2026-06-09T14:00:00Z" },
];

const orderComments: ActivityComment[] = [
  { id: "cmt_o001_1", entityType: "order", entityId: "ord_1001", author: "Call Center", authorInitials: "CC", body: "Customer called to confirm delivery address — verified.", at: "2026-06-08T11:30:00Z" },
];

const orderNotes: ActivityNote[] = [
  { id: "note_o001_1", entityType: "order", entityId: "ord_1001", author: "Manager", authorInitials: "MG", body: "VIP customer — priority shipping. Do not delay.", at: "2026-06-08T09:05:00Z" },
];

const orderFollowers: ActivityFollower[] = [
  { entityType: "order", entityId: "ord_1001", userId: "u1", name: "Sadia Rahman", initials: "SR" },
  { entityType: "order", entityId: "ord_1001", userId: "u4", name: "Call Center", initials: "CC" },
];

const orderAiActions: ActivityAiAction[] = [
  { id: "ai_o001_1", entityType: "order", entityId: "ord_1001", action: "AI Fraud Check", summary: "Low risk (12%). Verified customer, normal order pattern.", at: "2026-06-08T08:01:00Z" },
  { id: "ai_o001_2", entityType: "order", entityId: "ord_1001", action: "AI Delivery Prediction", summary: "Estimated delivery: June 11, 2026. 94% success probability.", at: "2026-06-09T14:05:00Z" },
];

// ─── Customer: cust_001 ──────────────────────────────────────────────────────

const customerEntries: ActivityEntry[] = [
  { id: "act_c001_1", entityType: "customer", entityId: "cust_001", actionType: "create", title: "Customer registered", actor: "System", actorInitials: "SY", at: "2025-08-15T10:00:00Z" },
  { id: "act_c001_2", entityType: "customer", entityId: "cust_001", actionType: "update", title: "Order created", description: "Order #ORD-1001 — ৳12,500", actor: "System", actorInitials: "SY", at: "2026-06-08T08:00:00Z" },
  { id: "act_c001_3", entityType: "customer", entityId: "cust_001", actionType: "update", title: "Wallet updated", fieldChanges: [{ field: "Wallet Balance", oldValue: "৳500", newValue: "৳750" }], actor: "System", actorInitials: "SY", at: "2026-06-01T12:00:00Z" },
  { id: "act_c001_4", entityType: "customer", entityId: "cust_001", actionType: "ai_action", title: "AI segment updated", description: "Moved to Gold tier segment based on purchase history", actor: "AI Agent", actorInitials: "AI", at: "2026-05-20T09:00:00Z" },
];

const customerComments: ActivityComment[] = [
  { id: "cmt_c001_1", entityType: "customer", entityId: "cust_001", author: "Sales Team", authorInitials: "ST", body: "High-value customer — offer loyalty discount on next purchase.", at: "2026-06-05T14:00:00Z" },
];

const customerFollowers: ActivityFollower[] = [
  { entityType: "customer", entityId: "cust_001", userId: "u5", name: "Sales Team", initials: "ST" },
];

const customerAiActions: ActivityAiAction[] = [
  { id: "ai_c001_1", entityType: "customer", entityId: "cust_001", action: "AI Segment Updated", summary: "Customer classified as Gold tier. Churn risk: Low (8%).", at: "2026-05-20T09:00:00Z" },
];

// ─── Review: rev_001 ─────────────────────────────────────────────────────────

const reviewEntries: ActivityEntry[] = [
  { id: "act_r001_1", entityType: "review", entityId: "rev_001", actionType: "create", title: "Review submitted", actor: "Rakibul Hasan", actorInitials: "RH", at: "2026-06-10T10:00:00Z" },
  { id: "act_r001_2", entityType: "review", entityId: "rev_001", actionType: "ai_action", title: "AI analysis completed", description: "Sentiment: Positive (94%). No spam detected.", actor: "AI Agent", actorInitials: "AI", at: "2026-06-10T10:01:00Z" },
  { id: "act_r001_3", entityType: "review", entityId: "rev_001", actionType: "approval", title: "Review approved", actor: "Sumaiya Akter", actorInitials: "SA", at: "2026-06-10T10:15:00Z" },
];

const reviewNotes: ActivityNote[] = [
  { id: "note_r001_1", entityType: "review", entityId: "rev_001", author: "Sumaiya Akter", authorInitials: "SA", body: "High-trust customer, verified purchase. Fast-tracked approval.", at: "2026-06-10T10:14:00Z" },
];

const reviewAiActions: ActivityAiAction[] = [
  { id: "ai_r001_1", entityType: "review", entityId: "rev_001", action: "AI Sentiment Analysis", summary: "Positive (94%). Display and performance praised.", at: "2026-06-10T10:01:00Z" },
];

// ─── Generic fallback entries for other entities ─────────────────────────────

function genericProductEntries(id: string): ActivityEntry[] {
  return [
    {
      id: `act_${id}_create`,
      entityType: "product",
      entityId: id,
      actionType: "create",
      title: "Product created",
      actor: "System",
      actorInitials: "SY",
      at: "2026-03-01T08:00:00Z",
    },
    {
      id: `act_${id}_update`,
      entityType: "product",
      entityId: id,
      actionType: "update",
      title: "Product updated",
      description: "Catalog sync completed",
      actor: "Admin",
      actorInitials: "AD",
      at: "2026-05-15T12:00:00Z",
    },
  ];
}

function genericOrderEntries(id: string): ActivityEntry[] {
  return [
    { id: `act_${id}_create`, entityType: "order", entityId: id, actionType: "create", title: "Order created", actor: "System", actorInitials: "SY", at: "2026-06-01T08:00:00Z" },
  ];
}

function genericCustomerEntries(id: string): ActivityEntry[] {
  return [
    { id: `act_${id}_create`, entityType: "customer", entityId: id, actionType: "create", title: "Customer registered", actor: "System", actorInitials: "SY", at: "2026-01-01T08:00:00Z" },
  ];
}

function genericReviewEntries(id: string): ActivityEntry[] {
  return [
    { id: `act_${id}_create`, entityType: "review", entityId: id, actionType: "create", title: "Review submitted", actor: "Customer", actorInitials: "CU", at: "2026-06-01T08:00:00Z" },
  ];
}

// ─── Exports ─────────────────────────────────────────────────────────────────

export const activityEntriesSeed: ActivityEntry[] = [
  ...productEntries,
  ...orderEntries,
  ...customerEntries,
  ...reviewEntries,
];

export const activityCommentsSeed: ActivityComment[] = [
  ...productComments,
  ...orderComments,
  ...customerComments,
];

export const activityNotesSeed: ActivityNote[] = [
  ...productNotes,
  ...orderNotes,
  ...reviewNotes,
];

export const activityAttachmentsSeed: ActivityAttachment[] = [...productAttachments];

export const activityFollowersSeed: ActivityFollower[] = [
  ...productFollowers,
  ...orderFollowers,
  ...customerFollowers,
];

export const activityAiActionsSeed: ActivityAiAction[] = [
  ...productAiActions,
  ...orderAiActions,
  ...customerAiActions,
  ...reviewAiActions,
];

export const activityApprovalsSeed: ActivityApproval[] = [...productApprovals];

/** Resolve activities for any entity — returns rich data for known IDs, generic fallback otherwise */
export function getSeedActivitiesForEntity(
  entityType: ActivityEntry["entityType"],
  entityId: string,
): ActivityEntry[] {
  const existing = activityEntriesSeed.filter(
    (e) => e.entityType === entityType && e.entityId === entityId,
  );
  if (existing.length > 0) return existing;

  switch (entityType) {
    case "product":
      return genericProductEntries(entityId);
    case "order":
      return genericOrderEntries(entityId);
    case "customer":
      return genericCustomerEntries(entityId);
    case "review":
      return genericReviewEntries(entityId);
    default:
      return [
        {
          id: `act_${entityType}_${entityId}_create`,
          entityType,
          entityId,
          actionType: "create",
          title: "Record created",
          actor: "System",
          actorInitials: "SY",
          at: new Date().toISOString(),
        },
      ];
  }
}

export function filterByEntity<T extends { entityType: ActivityEntry["entityType"]; entityId: string }>(
  items: T[],
  entityType: ActivityEntry["entityType"],
  entityId: string,
): T[] {
  return items.filter((i) => i.entityType === entityType && i.entityId === entityId);
}
