import type {
  ConfiguratorAnalyticsKpi,
  ConfiguratorCategory,
  ConfiguratorProfile,
  ConfiguratorTemplate,
  SavedBuild,
} from "@/lib/configurator/types";

export const configuratorProfilesSeed: ConfiguratorProfile[] = [
  {
    id: "cfg_pc",
    name: "PC Builder",
    slug: "pc-builder",
    profileType: "pc_builder",
    description: "Desktop PC configurator — CPU, motherboard, RAM, GPU, storage, PSU, case.",
    isDefault: true,
    status: "active",
    categoryCount: 8,
    ruleCount: 4,
    templateCount: 3,
    buildCount: 142,
    updatedAt: "2026-06-14",
    createdAt: "2026-01-10",
  },
  {
    id: "cfg_laptop",
    name: "Laptop Builder",
    slug: "laptop-builder",
    profileType: "laptop_builder",
    description: "Custom laptop configurator with chassis, display, and upgrade slots.",
    isDefault: false,
    status: "active",
    categoryCount: 6,
    ruleCount: 2,
    templateCount: 2,
    buildCount: 38,
    updatedAt: "2026-06-12",
    createdAt: "2026-02-01",
  },
  {
    id: "cfg_cctv",
    name: "CCTV Builder",
    slug: "cctv-builder",
    profileType: "cctv_builder",
    description: "Surveillance kit builder — cameras, NVR, cables, storage.",
    isDefault: false,
    status: "draft",
    categoryCount: 5,
    ruleCount: 1,
    templateCount: 1,
    buildCount: 12,
    updatedAt: "2026-06-10",
    createdAt: "2026-03-15",
  },
];

export const configuratorCategoriesSeed: ConfiguratorCategory[] = [
  {
    id: "cc_cpu",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Processor (CPU)",
    slug: "cpu",
    description: "Intel and AMD processors",
    sortOrder: 1,
    isRequired: true,
    selectionMode: "single",
    productCount: 48,
    status: "active",
    updatedAt: "2026-06-14",
  },
  {
    id: "cc_mobo",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Motherboard",
    slug: "motherboard",
    sortOrder: 2,
    isRequired: true,
    selectionMode: "single",
    productCount: 36,
    status: "active",
    updatedAt: "2026-06-14",
  },
  {
    id: "cc_ram",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Memory (RAM)",
    slug: "ram",
    sortOrder: 3,
    isRequired: true,
    selectionMode: "single",
    productCount: 52,
    status: "active",
    updatedAt: "2026-06-13",
  },
  {
    id: "cc_gpu",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Graphics Card",
    slug: "gpu",
    sortOrder: 4,
    isRequired: false,
    selectionMode: "single",
    productCount: 28,
    status: "active",
    updatedAt: "2026-06-12",
  },
  {
    id: "cc_storage",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Storage",
    slug: "storage",
    sortOrder: 5,
    isRequired: true,
    selectionMode: "multiple",
    productCount: 64,
    status: "active",
    updatedAt: "2026-06-11",
  },
  {
    id: "cc_psu",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Power Supply",
    slug: "psu",
    sortOrder: 6,
    isRequired: true,
    selectionMode: "single",
    productCount: 22,
    status: "active",
    updatedAt: "2026-06-10",
  },
  {
    id: "cc_case",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Case",
    slug: "case",
    sortOrder: 7,
    isRequired: true,
    selectionMode: "single",
    productCount: 18,
    status: "active",
    updatedAt: "2026-06-09",
  },
  {
    id: "cc_cooler",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "CPU Cooler",
    slug: "cooler",
    sortOrder: 8,
    isRequired: false,
    selectionMode: "single",
    productCount: 24,
    status: "draft",
    updatedAt: "2026-06-08",
  },
  {
    id: "cc_laptop_chassis",
    profileId: "cfg_laptop",
    profileName: "Laptop Builder",
    name: "Chassis",
    slug: "chassis",
    sortOrder: 1,
    isRequired: true,
    selectionMode: "single",
    productCount: 8,
    status: "active",
    updatedAt: "2026-06-07",
  },
];

export const configuratorTemplatesSeed: ConfiguratorTemplate[] = [
  {
    id: "ct_gaming",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Gaming Starter",
    slug: "gaming-starter",
    description: "Mid-range gaming build with RTX 4060",
    components: [
      { categoryId: "cc_cpu", categoryName: "Processor", productName: "Intel Core i5-14600K", quantity: 1 },
      { categoryId: "cc_mobo", categoryName: "Motherboard", productName: "ASUS Z790-P", quantity: 1 },
      { categoryId: "cc_ram", categoryName: "RAM", productName: "Corsair 32GB DDR5 5600", quantity: 1 },
      { categoryId: "cc_gpu", categoryName: "GPU", productName: "NVIDIA RTX 4060", quantity: 1 },
    ],
    isFeatured: true,
    status: "active",
    useCount: 56,
    updatedAt: "2026-06-14",
  },
  {
    id: "ct_office",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Office Productivity",
    slug: "office-productivity",
    description: "Quiet office workstation without dedicated GPU",
    components: [
      { categoryId: "cc_cpu", categoryName: "Processor", productName: "Intel Core i3-14100", quantity: 1 },
      { categoryId: "cc_mobo", categoryName: "Motherboard", productName: "MSI B760M", quantity: 1 },
      { categoryId: "cc_ram", categoryName: "RAM", productName: "Kingston 16GB DDR4", quantity: 1 },
    ],
    isFeatured: false,
    status: "active",
    useCount: 34,
    updatedAt: "2026-06-13",
  },
  {
    id: "ct_workstation",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Creative Workstation",
    slug: "creative-workstation",
    components: [
      { categoryId: "cc_cpu", categoryName: "Processor", productName: "AMD Ryzen 9 7950X", quantity: 1 },
      { categoryId: "cc_ram", categoryName: "RAM", productName: "G.Skill 64GB DDR5", quantity: 1 },
      { categoryId: "cc_gpu", categoryName: "GPU", productName: "NVIDIA RTX 4070 Ti", quantity: 1 },
    ],
    isFeatured: true,
    status: "draft",
    useCount: 8,
    updatedAt: "2026-06-12",
  },
];

export const savedBuildsSeed: SavedBuild[] = [
  {
    id: "sb_001",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Rahim's Gaming PC",
    buildCode: "PC-2026-0142",
    customerName: "Rahim Ahmed",
    components: [
      { categoryId: "cc_cpu", categoryName: "CPU", productName: "Intel i5-14600K", quantity: 1 },
      { categoryId: "cc_gpu", categoryName: "GPU", productName: "RTX 4060", quantity: 1 },
    ],
    totalPrice: 98500,
    compatibilityStatus: "compatible",
    status: "saved",
    updatedAt: "2026-06-15",
    createdAt: "2026-06-14",
  },
  {
    id: "sb_002",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Office Build #7",
    buildCode: "PC-2026-0138",
    customerName: "TechGadgets BD",
    components: [
      { categoryId: "cc_cpu", categoryName: "CPU", productName: "Intel i3-14100", quantity: 1 },
    ],
    totalPrice: 42000,
    compatibilityStatus: "warning",
    status: "ordered",
    updatedAt: "2026-06-14",
    createdAt: "2026-06-13",
  },
  {
    id: "sb_003",
    profileId: "cfg_pc",
    profileName: "PC Builder",
    name: "Socket mismatch test",
    buildCode: "PC-2026-0135",
    userName: "Guest",
    components: [
      { categoryId: "cc_cpu", categoryName: "CPU", productName: "AMD Ryzen 7", quantity: 1 },
      { categoryId: "cc_mobo", categoryName: "Motherboard", productName: "Intel Z790", quantity: 1 },
    ],
    totalPrice: 0,
    compatibilityStatus: "incompatible",
    status: "abandoned",
    updatedAt: "2026-06-12",
    createdAt: "2026-06-12",
  },
  {
    id: "sb_004",
    profileId: "cfg_laptop",
    profileName: "Laptop Builder",
    name: "Student Laptop",
    buildCode: "LP-2026-0008",
    customerName: "Nadia Islam",
    components: [
      { categoryId: "cc_laptop_chassis", categoryName: "Chassis", productName: "14\" Ultrabook Shell", quantity: 1 },
    ],
    totalPrice: 55000,
    compatibilityStatus: "compatible",
    status: "draft",
    updatedAt: "2026-06-11",
    createdAt: "2026-06-11",
  },
];

export function configuratorAnalyticsKpis(
  profiles = configuratorProfilesSeed,
  builds = savedBuildsSeed,
  templates = configuratorTemplatesSeed,
): ConfiguratorAnalyticsKpi[] {
  const totalBuilds = builds.length;
  const ordered = builds.filter((b) => b.status === "ordered").length;
  const incompatible = builds.filter((b) => b.compatibilityStatus === "incompatible").length;
  const featuredTemplates = templates.filter((t) => t.isFeatured && t.status === "active").length;

  return [
    { label: "Active profiles", value: profiles.filter((p) => p.status === "active").length, sub: `${profiles.length} total` },
    { label: "Saved builds", value: totalBuilds, sub: `${ordered} converted to orders`, trend: "up" },
    { label: "Rule violations", value: incompatible, sub: "Incompatible builds blocked", trend: incompatible > 0 ? "down" : "flat" },
    { label: "Featured templates", value: featuredTemplates, sub: `${templates.reduce((s, t) => s + t.useCount, 0)} template uses`, trend: "up" },
  ];
}

export function formatBdt(amount: number): string {
  return `৳${amount.toLocaleString("en-BD")}`;
}
