import type { PcBuilderProduct } from "@/lib/builder/types";

const img = (seed: string) => `https://picsum.photos/seed/${seed}/400/400`;

/** Extras + peripherals mock catalog — optional slots, no compatibility rules */
export const pcBuilderExtrasProductsSeed: PcBuilderProduct[] = [
  // OS
  {
    id: "pcb_os_win11_home",
    slug: "windows-11-home",
    name: "Windows 11 Home (USB)",
    brand: "Microsoft",
    price: 12500,
    stock: 40,
    stockStatus: "In Stock",
    image: img("os-win11"),
    stepId: "os",
    categoryId: "cc_os",
    attributeProfileId: "cap_os",
    attributes: { edition: "home" },
    specs: [{ label: "Edition", value: "Home" }, { label: "Delivery", value: "USB key" }],
  },
  {
    id: "pcb_os_win11_pro",
    slug: "windows-11-pro",
    name: "Windows 11 Pro (USB)",
    brand: "Microsoft",
    price: 18900,
    stock: 22,
    stockStatus: "In Stock",
    image: img("os-win11-pro"),
    stepId: "os",
    categoryId: "cc_os",
    attributeProfileId: "cap_os",
    attributes: { edition: "pro" },
    specs: [{ label: "Edition", value: "Pro" }],
  },
  // Case fans
  {
    id: "pcb_fan_120_rgb",
    slug: "corsair-ll120-rgb",
    name: "Corsair LL120 RGB (3-pack)",
    brand: "Corsair",
    price: 8900,
    stock: 18,
    stockStatus: "In Stock",
    image: img("fan-rgb"),
    stepId: "case_fans",
    categoryId: "cc_fans",
    attributeProfileId: "cap_fans",
    attributes: { size_mm: 120, rgb: true },
    specs: [{ label: "Size", value: "120mm" }, { label: "Pack", value: "3 fans" }],
  },
  {
    id: "pcb_fan_140",
    slug: "noctua-nf-a14",
    name: "Noctua NF-A14 PWM",
    brand: "Noctua",
    price: 3200,
    stock: 30,
    stockStatus: "In Stock",
    image: img("fan-140"),
    stepId: "case_fans",
    categoryId: "cc_fans",
    attributeProfileId: "cap_fans",
    attributes: { size_mm: 140, rgb: false },
    specs: [{ label: "Size", value: "140mm" }],
  },
  // WiFi
  {
    id: "pcb_wifi_ax3000",
    slug: "tp-link-ax3000",
    name: "TP-Link Archer TX3000E WiFi 6",
    brand: "TP-Link",
    price: 4500,
    stock: 25,
    stockStatus: "In Stock",
    image: img("wifi-ax"),
    stepId: "wifi",
    categoryId: "cc_wifi",
    attributeProfileId: "cap_wifi",
    attributes: { standard: "wifi6" },
    specs: [{ label: "Standard", value: "WiFi 6" }],
  },
  // Accessories
  {
    id: "pcb_acc_thermal",
    slug: "thermal-grizzly-kryonaut",
    name: "Thermal Grizzly Kryonaut 1g",
    brand: "Thermal Grizzly",
    price: 850,
    stock: 50,
    stockStatus: "In Stock",
    image: img("thermal"),
    stepId: "accessories",
    categoryId: "cc_accessories",
    attributeProfileId: "cap_accessories",
    attributes: { type: "thermal_paste" },
    specs: [{ label: "Type", value: "Thermal paste" }],
  },
  {
    id: "pcb_acc_cables",
    slug: "cablemod-pro-kit",
    name: "CableMod Pro ModMesh Cable Kit",
    brand: "CableMod",
    price: 6200,
    stock: 8,
    stockStatus: "Low Stock",
    image: img("cables"),
    stepId: "accessories",
    categoryId: "cc_accessories",
    attributeProfileId: "cap_accessories",
    attributes: { type: "cables" },
    specs: [{ label: "Type", value: "PSU extension kit" }],
  },
  // Mouse
  {
    id: "pcb_mouse_gpro",
    slug: "logitech-g-pro-x-superlight",
    name: "Logitech G Pro X Superlight",
    brand: "Logitech",
    price: 12900,
    stock: 15,
    stockStatus: "In Stock",
    image: img("mouse-gpro"),
    stepId: "mouse",
    categoryId: "cc_mouse",
    attributeProfileId: "cap_mouse",
    attributes: { wireless: true },
    specs: [{ label: "Weight", value: "63g" }],
  },
  {
    id: "pcb_mouse_rival",
    slug: "steelseries-rival-3",
    name: "SteelSeries Rival 3",
    brand: "SteelSeries",
    price: 3500,
    stock: 28,
    stockStatus: "In Stock",
    image: img("mouse-rival"),
    stepId: "mouse",
    categoryId: "cc_mouse",
    attributeProfileId: "cap_mouse",
    attributes: { wireless: false },
    specs: [{ label: "Type", value: "Wired" }],
  },
  // Keyboard
  {
    id: "pcb_kb_g915",
    slug: "logitech-g915-tkl",
    name: "Logitech G915 TKL Wireless",
    brand: "Logitech",
    price: 18900,
    stock: 10,
    stockStatus: "Low Stock",
    image: img("kb-g915"),
    stepId: "keyboard",
    categoryId: "cc_keyboard",
    attributeProfileId: "cap_keyboard",
    attributes: { switches: "low_profile", wireless: true },
    specs: [{ label: "Layout", value: "TKL" }],
  },
  {
    id: "pcb_kb_akko",
    slug: "akko-5075b",
    name: "Akko 5075B Plus (Bangla layout)",
    brand: "Akko",
    price: 8900,
    stock: 20,
    stockStatus: "In Stock",
    image: img("kb-akko"),
    stepId: "keyboard",
    categoryId: "cc_keyboard",
    attributeProfileId: "cap_keyboard",
    attributes: { switches: "mechanical", wireless: true },
    specs: [{ label: "Layout", value: "75%" }],
  },
  // Mouse pad
  {
    id: "pcb_pad_xl",
    slug: "steelseries-qck-heavy-xl",
    name: "SteelSeries QcK Heavy XL",
    brand: "SteelSeries",
    price: 2800,
    stock: 35,
    stockStatus: "In Stock",
    image: img("pad-xl"),
    stepId: "mousepad",
    categoryId: "cc_mousepad",
    attributeProfileId: "cap_mousepad",
    attributes: { size: "xl" },
    specs: [{ label: "Size", value: "XL" }],
  },
  // Controller
  {
    id: "pcb_ctrl_xbox",
    slug: "xbox-wireless-controller",
    name: "Xbox Wireless Controller",
    brand: "Microsoft",
    price: 6500,
    stock: 24,
    stockStatus: "In Stock",
    image: img("ctrl-xbox"),
    stepId: "controller",
    categoryId: "cc_controller",
    attributeProfileId: "cap_controller",
    attributes: { platform: "xbox_pc" },
    specs: [{ label: "Connectivity", value: "Bluetooth + USB" }],
  },
  // Headset
  {
    id: "pcb_headset_hs80",
    slug: "corsair-hs80-rgb",
    name: "Corsair HS80 RGB Wireless",
    brand: "Corsair",
    price: 11500,
    stock: 12,
    stockStatus: "In Stock",
    image: img("hs80"),
    stepId: "headset",
    categoryId: "cc_headset",
    attributeProfileId: "cap_headset",
    attributes: { wireless: true },
    specs: [{ label: "Type", value: "Wireless" }],
  },
  // Microphone
  {
    id: "pcb_mic_mv7",
    slug: "shure-mv7",
    name: "Shure MV7 USB/XLR Microphone",
    brand: "Shure",
    price: 24900,
    stock: 6,
    stockStatus: "Low Stock",
    image: img("mic-mv7"),
    stepId: "microphone",
    categoryId: "cc_mic",
    attributeProfileId: "cap_mic",
    attributes: { type: "dynamic" },
    specs: [{ label: "Connection", value: "USB + XLR" }],
  },
  // Speakers
  {
    id: "pcb_spk_mx",
    slug: "edifier-mx-bt",
    name: "Edifier MX3.0 BT Desktop Speakers",
    brand: "Edifier",
    price: 5200,
    stock: 18,
    stockStatus: "In Stock",
    image: img("spk-edifier"),
    stepId: "speakers",
    categoryId: "cc_speakers",
    attributeProfileId: "cap_speakers",
    attributes: { channels: 2.1 },
    specs: [{ label: "Channels", value: "2.1" }],
  },
  // Webcam
  {
    id: "pcb_cam_c920",
    slug: "logitech-c920",
    name: "Logitech C920 HD Pro Webcam",
    brand: "Logitech",
    price: 7800,
    stock: 14,
    stockStatus: "In Stock",
    image: img("cam-c920"),
    stepId: "webcam",
    categoryId: "cc_webcam",
    attributeProfileId: "cap_webcam",
    attributes: { resolution: "1080p" },
    specs: [{ label: "Resolution", value: "1080p" }],
  },
];
