import type { PcBuilderProduct, PcBuilderSelection, PcBuilderStepId } from "@/lib/builder/types";
import { coolerProductsSeed } from "@/lib/mock-data/pc-builder-coolers";
import { pcBuilderExtrasProductsSeed } from "@/lib/mock-data/pc-builder-extras-products";

const img = (seed: string) => `https://picsum.photos/seed/${seed}/400/400`;

export const pcBuilderProductsSeed: PcBuilderProduct[] = [
  // CPU
  {
    id: "pcb_cpu_i5",
    slug: "intel-core-i5-14600k",
    name: "Intel Core i5-14600K",
    brand: "Intel",
    price: 28900,
    compareAtPrice: 31900,
    stock: 24,
    stockStatus: "In Stock",
    image: img("cpu-i5"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "lga_1700", tdp: 125, core_count: 14, generation: "14th" },
    specs: [{ label: "Cores", value: "14" }, { label: "Socket", value: "LGA 1700" }, { label: "TDP", value: "125W" }],
  },
  {
    id: "pcb_cpu_i7",
    slug: "intel-core-i7-14700k",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    price: 42900,
    stock: 12,
    stockStatus: "Low Stock",
    image: img("cpu-i7"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "lga_1700", tdp: 125, core_count: 20, generation: "14th" },
    specs: [{ label: "Cores", value: "20" }, { label: "Socket", value: "LGA 1700" }],
  },
  {
    id: "pcb_cpu_r7",
    slug: "amd-ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    price: 39900,
    stock: 8,
    stockStatus: "Low Stock",
    image: img("cpu-r7"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "am5", tdp: 120, core_count: 8, generation: "ryzen_7000" },
    specs: [{ label: "Cores", value: "8" }, { label: "Socket", value: "AM5" }],
  },
  {
    id: "pcb_cpu_r9",
    slug: "amd-ryzen-9-7950x",
    name: "AMD Ryzen 9 7950X",
    brand: "AMD",
    price: 54900,
    stock: 0,
    stockStatus: "Out of Stock",
    image: img("cpu-r9"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "am5", tdp: 170, core_count: 16, generation: "ryzen_7000" },
    specs: [{ label: "Cores", value: "16" }, { label: "Socket", value: "AM5" }, { label: "TDP", value: "170W" }],
  },
  {
    id: "pcb_cpu_r5",
    slug: "amd-ryzen-5-7600",
    name: "AMD Ryzen 5 7600",
    brand: "AMD",
    price: 21900,
    stock: 28,
    stockStatus: "In Stock",
    image: img("cpu-r5"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "am5", tdp: 65, core_count: 6, generation: "ryzen_7000" },
    specs: [{ label: "Cores", value: "6" }, { label: "Socket", value: "AM5" }, { label: "TDP", value: "65W" }],
  },
  {
    id: "pcb_cpu_i3",
    slug: "intel-core-i3-14100",
    name: "Intel Core i3-14100",
    brand: "Intel",
    price: 14200,
    stock: 36,
    stockStatus: "In Stock",
    image: img("cpu-i3"),
    stepId: "cpu",
    categoryId: "cc_cpu",
    attributeProfileId: "cap_cpu",
    attributes: { socket: "lga_1700", tdp: 60, core_count: 4, generation: "14th" },
    specs: [{ label: "Cores", value: "4" }, { label: "Socket", value: "LGA 1700" }, { label: "TDP", value: "60W" }],
  },
  // Motherboard
  {
    id: "pcb_mobo_z790",
    slug: "asus-z790-p-wifi",
    name: "ASUS Z790-P WiFi",
    brand: "ASUS",
    price: 24500,
    stock: 18,
    stockStatus: "In Stock",
    image: img("mobo-z790"),
    stepId: "motherboard",
    categoryId: "cc_mobo",
    attributeProfileId: "cap_mobo",
    attributes: { socket: "lga_1700", ram_type: "ddr5", chipset: "z790" },
    specs: [{ label: "Socket", value: "LGA 1700" }, { label: "RAM", value: "DDR5" }],
  },
  {
    id: "pcb_mobo_b760",
    slug: "msi-b760m-pro",
    name: "MSI B760M PRO",
    brand: "MSI",
    price: 16500,
    stock: 32,
    stockStatus: "In Stock",
    image: img("mobo-b760"),
    stepId: "motherboard",
    categoryId: "cc_mobo",
    attributeProfileId: "cap_mobo",
    attributes: { socket: "lga_1700", ram_type: "ddr4", chipset: "b760" },
    specs: [{ label: "Socket", value: "LGA 1700" }, { label: "RAM", value: "DDR4" }],
  },
  {
    id: "pcb_mobo_b650",
    slug: "gigabyte-b650-aorus",
    name: "Gigabyte B650 AORUS",
    brand: "Gigabyte",
    price: 18900,
    stock: 15,
    stockStatus: "In Stock",
    image: img("mobo-b650"),
    stepId: "motherboard",
    categoryId: "cc_mobo",
    attributeProfileId: "cap_mobo",
    attributes: { socket: "am5", ram_type: "ddr5", chipset: "b650" },
    specs: [{ label: "Socket", value: "AM5" }, { label: "RAM", value: "DDR5" }],
  },
  {
    id: "pcb_mobo_b650m",
    slug: "asrock-b650m-pro-rs",
    name: "ASRock B650M Pro RS",
    brand: "ASRock",
    price: 14200,
    stock: 22,
    stockStatus: "In Stock",
    image: img("mobo-b650m"),
    stepId: "motherboard",
    categoryId: "cc_mobo",
    attributeProfileId: "cap_mobo",
    attributes: { socket: "am5", ram_type: "ddr5", chipset: "b650" },
    specs: [{ label: "Socket", value: "AM5" }, { label: "Form", value: "mATX" }],
  },
  {
    id: "pcb_mobo_b760_ddr5",
    slug: "msi-b760m-mortar-ddr5",
    name: "MSI MAG B760M Mortar DDR5",
    brand: "MSI",
    price: 17800,
    stock: 26,
    stockStatus: "In Stock",
    image: img("mobo-b760-ddr5"),
    stepId: "motherboard",
    categoryId: "cc_mobo",
    attributeProfileId: "cap_mobo",
    attributes: { socket: "lga_1700", ram_type: "ddr5", chipset: "b760" },
    specs: [{ label: "Socket", value: "LGA 1700" }, { label: "RAM", value: "DDR5" }],
  },
  // RAM
  {
    id: "pcb_ram_ddr5_32",
    slug: "corsair-vengeance-32gb-ddr5",
    name: "Corsair Vengeance 32GB DDR5 5600",
    brand: "Corsair",
    price: 9800,
    stock: 40,
    stockStatus: "In Stock",
    image: img("ram-ddr5"),
    stepId: "ram",
    categoryId: "cc_ram",
    attributeProfileId: "cap_ram",
    attributes: { type: "ddr5", speed: 5600, capacity: 32 },
    specs: [{ label: "Type", value: "DDR5" }, { label: "Speed", value: "5600 MHz" }],
  },
  {
    id: "pcb_ram_ddr5_16",
    slug: "kingston-fury-16gb-ddr5",
    name: "Kingston Fury 16GB DDR5 5200",
    brand: "Kingston",
    price: 5200,
    stock: 55,
    stockStatus: "In Stock",
    image: img("ram-ddr5-16"),
    stepId: "ram",
    categoryId: "cc_ram",
    attributeProfileId: "cap_ram",
    attributes: { type: "ddr5", speed: 5200, capacity: 16 },
    specs: [{ label: "Type", value: "DDR5" }, { label: "Capacity", value: "16 GB" }],
  },
  {
    id: "pcb_ram_ddr4_32",
    slug: "crucial-32gb-ddr4",
    name: "Crucial 32GB DDR4 3200",
    brand: "Crucial",
    price: 7200,
    stock: 28,
    stockStatus: "In Stock",
    image: img("ram-ddr4"),
    stepId: "ram",
    categoryId: "cc_ram",
    attributeProfileId: "cap_ram",
    attributes: { type: "ddr4", speed: 3200, capacity: 32 },
    specs: [{ label: "Type", value: "DDR4" }],
  },
  {
    id: "pcb_ram_ddr4_16",
    slug: "kingston-16gb-ddr4-3200",
    name: "Kingston Fury 16GB DDR4 3200",
    brand: "Kingston",
    price: 3800,
    stock: 48,
    stockStatus: "In Stock",
    image: img("ram-ddr4-16"),
    stepId: "ram",
    categoryId: "cc_ram",
    attributeProfileId: "cap_ram",
    attributes: { type: "ddr4", speed: 3200, capacity: 16 },
    specs: [{ label: "Type", value: "DDR4" }, { label: "Capacity", value: "16 GB" }],
  },
  {
    id: "pcb_ram_ddr5_64",
    slug: "gskill-64gb-ddr5-6000",
    name: "G.Skill Trident Z 64GB DDR5 6000",
    brand: "G.Skill",
    price: 18500,
    stock: 12,
    stockStatus: "In Stock",
    image: img("ram-ddr5-64"),
    stepId: "ram",
    categoryId: "cc_ram",
    attributeProfileId: "cap_ram",
    attributes: { type: "ddr5", speed: 6000, capacity: 64 },
    specs: [{ label: "Type", value: "DDR5" }, { label: "Capacity", value: "64 GB" }],
  },
  // GPU
  {
    id: "pcb_gpu_4060",
    slug: "nvidia-rtx-4060",
    name: "NVIDIA GeForce RTX 4060 8GB",
    brand: "NVIDIA",
    price: 38500,
    stock: 14,
    stockStatus: "In Stock",
    image: img("gpu-4060"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 8, tdp: 115, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "8 GB" }, { label: "TDP", value: "115W" }],
  },
  {
    id: "pcb_gpu_4070",
    slug: "nvidia-rtx-4070",
    name: "NVIDIA GeForce RTX 4070 12GB",
    brand: "NVIDIA",
    price: 58900,
    stock: 6,
    stockStatus: "Low Stock",
    image: img("gpu-4070"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 12, tdp: 200, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "12 GB" }],
  },
  {
    id: "pcb_gpu_7800xt",
    slug: "amd-rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    price: 52000,
    stock: 9,
    stockStatus: "In Stock",
    image: img("gpu-7800"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 16, tdp: 263, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "16 GB" }],
  },
  {
    id: "pcb_gpu_3050",
    slug: "nvidia-rtx-3050",
    name: "NVIDIA GeForce RTX 3050 8GB",
    brand: "NVIDIA",
    price: 26500,
    stock: 20,
    stockStatus: "In Stock",
    image: img("gpu-3050"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 8, tdp: 130, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "8 GB" }, { label: "TDP", value: "130W" }],
  },
  {
    id: "pcb_gpu_4060ti",
    slug: "nvidia-rtx-4060-ti",
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    price: 48500,
    stock: 11,
    stockStatus: "In Stock",
    image: img("gpu-4060ti"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 16, tdp: 165, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "16 GB" }],
  },
  {
    id: "pcb_gpu_7600",
    slug: "amd-rx-7600",
    name: "AMD Radeon RX 7600 8GB",
    brand: "AMD",
    price: 32800,
    stock: 16,
    stockStatus: "In Stock",
    image: img("gpu-7600"),
    stepId: "gpu",
    categoryId: "cc_gpu",
    attributeProfileId: "cap_gpu",
    attributes: { vram: 8, tdp: 165, pcie: "4.0" },
    specs: [{ label: "VRAM", value: "8 GB" }],
  },
  // SSD
  {
    id: "pcb_ssd_1tb",
    slug: "samsung-990-pro-1tb",
    name: "Samsung 990 PRO 1TB NVMe",
    brand: "Samsung",
    price: 12500,
    stock: 45,
    stockStatus: "In Stock",
    image: img("ssd-1tb"),
    stepId: "ssd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "nvme", capacity: 1000, form_factor: "m2" },
    specs: [{ label: "Capacity", value: "1 TB" }, { label: "Interface", value: "NVMe" }],
  },
  {
    id: "pcb_ssd_2tb",
    slug: "wd-black-sn850x-2tb",
    name: "WD Black SN850X 2TB",
    brand: "WD",
    price: 19800,
    stock: 22,
    stockStatus: "In Stock",
    image: img("ssd-2tb"),
    stepId: "ssd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "nvme", capacity: 2000, form_factor: "m2" },
    specs: [{ label: "Capacity", value: "2 TB" }],
  },
  {
    id: "pcb_ssd_500",
    slug: "kingston-nv2-500gb",
    name: "Kingston NV2 500GB NVMe",
    brand: "Kingston",
    price: 5200,
    stock: 60,
    stockStatus: "In Stock",
    image: img("ssd-500"),
    stepId: "ssd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "nvme", capacity: 500, form_factor: "m2" },
    specs: [{ label: "Capacity", value: "500 GB" }],
  },
  {
    id: "pcb_ssd_1tb_budget",
    slug: "crucial-p3-1tb",
    name: "Crucial P3 1TB NVMe",
    brand: "Crucial",
    price: 8900,
    stock: 38,
    stockStatus: "In Stock",
    image: img("ssd-p3"),
    stepId: "ssd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "nvme", capacity: 1000, form_factor: "m2" },
    specs: [{ label: "Capacity", value: "1 TB" }, { label: "Budget", value: "Yes" }],
  },
  // HDD
  {
    id: "pcb_hdd_1tb",
    slug: "wd-blue-1tb",
    name: "WD Blue 1TB 7200RPM",
    brand: "WD",
    price: 4200,
    stock: 55,
    stockStatus: "In Stock",
    image: img("hdd-1tb"),
    stepId: "hdd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "sata", capacity: 1000, form_factor: "3.5" },
    specs: [{ label: "Capacity", value: "1 TB" }, { label: "RPM", value: "7200" }],
  },
  {
    id: "pcb_hdd_2tb",
    slug: "seagate-barracuda-2tb",
    name: "Seagate Barracuda 2TB",
    brand: "Seagate",
    price: 5800,
    stock: 40,
    stockStatus: "In Stock",
    image: img("hdd-2tb"),
    stepId: "hdd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "sata", capacity: 2000, form_factor: "3.5" },
    specs: [{ label: "Capacity", value: "2 TB" }],
  },
  {
    id: "pcb_hdd_3tb",
    slug: "toshiba-3tb",
    name: "Toshiba P300 3TB",
    brand: "Toshiba",
    price: 7200,
    stock: 22,
    stockStatus: "In Stock",
    image: img("hdd-3tb"),
    stepId: "hdd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "sata", capacity: 3000, form_factor: "3.5" },
    specs: [{ label: "Capacity", value: "3 TB" }],
  },
  {
    id: "pcb_hdd_4tb",
    slug: "wd-red-4tb",
    name: "WD Red Plus 4TB NAS",
    brand: "WD",
    price: 11200,
    stock: 18,
    stockStatus: "In Stock",
    image: img("hdd-4tb"),
    stepId: "hdd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "sata", capacity: 4000, form_factor: "3.5" },
    specs: [{ label: "Capacity", value: "4 TB" }],
  },
  {
    id: "pcb_hdd_8tb",
    slug: "seagate-ironwolf-8tb",
    name: "Seagate IronWolf 8TB",
    brand: "Seagate",
    price: 19800,
    stock: 10,
    stockStatus: "In Stock",
    image: img("hdd-8tb"),
    stepId: "hdd",
    categoryId: "cc_storage",
    attributeProfileId: "cap_storage",
    attributes: { interface: "sata", capacity: 8000, form_factor: "3.5" },
    specs: [{ label: "Capacity", value: "8 TB" }],
  },
  // PSU
  {
    id: "pcb_psu_650",
    slug: "corsair-rm650e",
    name: "Corsair RM650e 650W 80+ Gold",
    brand: "Corsair",
    price: 8900,
    stock: 30,
    stockStatus: "In Stock",
    image: img("psu-650"),
    stepId: "psu",
    categoryId: "cc_psu",
    attributeProfileId: "cap_psu",
    attributes: { wattage: 650, efficiency: "gold", modular: "semi" },
    specs: [{ label: "Wattage", value: "650W" }],
  },
  {
    id: "pcb_psu_850",
    slug: "seasonic-focus-850",
    name: "Seasonic Focus GX-850 80+ Gold",
    brand: "Seasonic",
    price: 13200,
    stock: 18,
    stockStatus: "In Stock",
    image: img("psu-850"),
    stepId: "psu",
    categoryId: "cc_psu",
    attributeProfileId: "cap_psu",
    attributes: { wattage: 850, efficiency: "gold", modular: "full" },
    specs: [{ label: "Wattage", value: "850W" }],
  },
  {
    id: "pcb_psu_550",
    slug: "evga-550-b3",
    name: "EVGA 550 B3 80+ Bronze",
    brand: "EVGA",
    price: 6200,
    stock: 42,
    stockStatus: "In Stock",
    image: img("psu-550"),
    stepId: "psu",
    categoryId: "cc_psu",
    attributeProfileId: "cap_psu",
    attributes: { wattage: 550, efficiency: "bronze", modular: "non" },
    specs: [{ label: "Wattage", value: "550W" }],
  },
  {
    id: "pcb_psu_750",
    slug: "corsair-rm750x",
    name: "Corsair RM750x 750W 80+ Gold",
    brand: "Corsair",
    price: 10800,
    stock: 24,
    stockStatus: "In Stock",
    image: img("psu-750"),
    stepId: "psu",
    categoryId: "cc_psu",
    attributeProfileId: "cap_psu",
    attributes: { wattage: 750, efficiency: "gold", modular: "full" },
    specs: [{ label: "Wattage", value: "750W" }],
  },
  // Case
  {
    id: "pcb_case_mid",
    slug: "nzxt-h5-flow",
    name: "NZXT H5 Flow Mid Tower",
    brand: "NZXT",
    price: 7800,
    stock: 20,
    stockStatus: "In Stock",
    image: img("case-mid"),
    stepId: "case",
    categoryId: "cc_case",
    attributeProfileId: "cap_case",
    attributes: { form_factor: "atx_mid", gpu_length_max: 365 },
    specs: [{ label: "Form", value: "ATX Mid" }],
  },
  {
    id: "pcb_case_compact",
    slug: "fractal-pop-mini",
    name: "Fractal Pop Mini Air",
    brand: "Fractal",
    price: 6500,
    stock: 12,
    stockStatus: "In Stock",
    image: img("case-mini"),
    stepId: "case",
    categoryId: "cc_case",
    attributeProfileId: "cap_case",
    attributes: { form_factor: "matx", gpu_length_max: 280 },
    specs: [{ label: "Form", value: "mATX" }],
  },
  {
    id: "pcb_case_4000d",
    slug: "corsair-4000d-airflow",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    price: 9200,
    stock: 18,
    stockStatus: "In Stock",
    image: img("case-4000d"),
    stepId: "case",
    categoryId: "cc_case",
    attributeProfileId: "cap_case",
    attributes: { form_factor: "atx_mid", gpu_length_max: 360 },
    specs: [{ label: "Form", value: "ATX Mid" }, { label: "GPU max", value: "360mm" }],
  },
  {
    id: "pcb_case_o11",
    slug: "lian-li-o11-dynamic",
    name: "Lian Li O11 Dynamic EVO",
    brand: "Lian Li",
    price: 14500,
    stock: 8,
    stockStatus: "In Stock",
    image: img("case-o11"),
    stepId: "case",
    categoryId: "cc_case",
    attributeProfileId: "cap_case",
    attributes: { form_factor: "atx_mid", gpu_length_max: 420 },
    specs: [{ label: "Form", value: "ATX Mid" }, { label: "Premium", value: "Yes" }],
  },
  // Monitor
  {
    id: "pcb_mon_27",
    slug: "lg-27-4k-144hz",
    name: 'LG UltraGear 27" 4K 144Hz',
    brand: "LG",
    price: 42000,
    stock: 10,
    stockStatus: "In Stock",
    image: img("mon-27"),
    stepId: "monitor",
    categoryId: "cc_monitor",
    attributeProfileId: "cap_monitor",
    attributes: { size: 27, resolution: "4k", refresh_rate: 144 },
    specs: [{ label: "Size", value: '27"' }, { label: "Resolution", value: "4K" }],
  },
  {
    id: "pcb_mon_24",
    slug: "dell-24-1080p",
    name: 'Dell 24" 1080p 165Hz',
    brand: "Dell",
    price: 18500,
    stock: 35,
    stockStatus: "In Stock",
    image: img("mon-24"),
    stepId: "monitor",
    categoryId: "cc_monitor",
    attributeProfileId: "cap_monitor",
    attributes: { size: 24, resolution: "1080p", refresh_rate: 165 },
    specs: [{ label: "Size", value: '24"' }],
  },
  {
    id: "pcb_mon_27_1440",
    slug: "aoc-27-1440p-165hz",
    name: 'AOC 27" 1440p 165Hz IPS',
    brand: "AOC",
    price: 28900,
    stock: 14,
    stockStatus: "In Stock",
    image: img("mon-27-1440"),
    stepId: "monitor",
    categoryId: "cc_monitor",
    attributeProfileId: "cap_monitor",
    attributes: { size: 27, resolution: "1440p", refresh_rate: 165 },
    specs: [{ label: "Size", value: '27"' }, { label: "Resolution", value: "1440p" }],
  },
  {
    id: "pcb_mon_34_uw",
    slug: "samsung-34-ultrawide",
    name: 'Samsung 34" Ultrawide 144Hz',
    brand: "Samsung",
    price: 52000,
    stock: 6,
    stockStatus: "Low Stock",
    image: img("mon-34"),
    stepId: "monitor",
    categoryId: "cc_monitor",
    attributeProfileId: "cap_monitor",
    attributes: { size: 34, resolution: "ultrawide", refresh_rate: 144 },
    specs: [{ label: "Size", value: '34"' }, { label: "Type", value: "Ultrawide" }],
  },
];

export function getPcProductsByStep(stepId: PcBuilderStepId): PcBuilderProduct[] {
  if (stepId === "cooler") {
    return coolerProductsSeed as PcBuilderProduct[];
  }
  const fromMain = pcBuilderProductsSeed.filter((p) => p.stepId === stepId);
  if (fromMain.length > 0) return fromMain;
  return pcBuilderExtrasProductsSeed.filter((p) => p.stepId === stepId);
}

export function getPcProductById(id: string): PcBuilderProduct | undefined {
  return (
    pcBuilderProductsSeed.find((p) => p.id === id) ??
    pcBuilderExtrasProductsSeed.find((p) => p.id === id) ??
    (coolerProductsSeed.find((c) => c.id === id) as PcBuilderProduct | undefined)
  );
}

export function selectionsToBuildContext(selections: PcBuilderSelection[]) {
  return selections.map((s) => ({
    componentProfileId: s.attributeProfileId,
    componentName: s.productName,
    productId: s.productId,
    attributes: s.attributes,
  }));
}
