export interface WebsitePage {
  id: string;
  title: string;
  slug: string;
  status: "draft" | "review" | "published";
  authorId: string;
  authorName: string;
  template: string;
  createdAt: string;
  publishedAt?: string;
  updatedAt: string;
  metaTitle?: string;
  metaDescription?: string;
  blocksCount: number;
  companyId: string;
}

export const mockWebsitePages: WebsitePage[] = [
  {
    id: "page-1",
    title: "Home",
    slug: "home",
    status: "published",
    authorId: "user-1",
    authorName: "Admin User",
    template: "Homepage Corporate",
    createdAt: "2026-01-01T00:00:00Z",
    publishedAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-06-15T12:00:00Z",
    metaTitle: "TechGadgets BD - Leading Technology & Gadgets Provider",
    metaDescription: "Welcome to TechGadgets BD. We provide high-quality technology solutions, products, and services to businesses and consumers.",
    blocksCount: 12,
    companyId: "co2",
  },
  {
    id: "page-2",
    title: "About Us",
    slug: "about",
    status: "published",
    authorId: "user-1",
    authorName: "Admin User",
    template: "Standard Text / Media",
    createdAt: "2026-01-01T00:00:00Z",
    publishedAt: "2026-01-02T11:00:00Z",
    updatedAt: "2026-06-10T14:30:00Z",
    metaTitle: "About Us | TechGadgets BD",
    metaDescription: "Learn more about TechGadgets BD's mission, values, history, and the amazing team driving our technology forward.",
    blocksCount: 6,
    companyId: "co2",
  },
  {
    id: "page-3",
    title: "Services",
    slug: "services",
    status: "published",
    authorId: "user-2",
    authorName: "Sarah Connor",
    template: "Service Catalog Grid",
    createdAt: "2026-01-05T09:00:00Z",
    publishedAt: "2026-01-06T15:00:00Z",
    updatedAt: "2026-06-01T09:15:00Z",
    metaTitle: "Enterprise IT Services & Consulting | TechGadgets BD",
    metaDescription: "Explore our range of professional services, including cloud migration, custom software development, and hardware procurement.",
    blocksCount: 8,
    companyId: "co2",
  },
  {
    id: "page-4",
    title: "Careers",
    slug: "careers",
    status: "published",
    authorId: "user-3",
    authorName: "John Doe",
    template: "Careers Hub",
    createdAt: "2026-02-10T08:00:00Z",
    publishedAt: "2026-02-12T14:00:00Z",
    updatedAt: "2026-06-18T16:00:00Z",
    metaTitle: "Join Our Team - Careers | TechGadgets BD",
    metaDescription: "Build the future of technology with us. Check out our open positions and discover why TechGadgets BD is a great place to work.",
    blocksCount: 7,
    companyId: "co2",
  },
  {
    id: "page-5",
    title: "Privacy Policy",
    slug: "privacy-policy",
    status: "published",
    authorId: "user-1",
    authorName: "Admin User",
    template: "Plain Document",
    createdAt: "2026-01-01T00:00:00Z",
    publishedAt: "2026-01-01T01:00:00Z",
    updatedAt: "2026-01-01T01:00:00Z",
    metaTitle: "Privacy Policy | TechGadgets BD",
    metaDescription: "Our privacy policy explains how we collect, use, and protect your personal information on our company website and services.",
    blocksCount: 4,
    companyId: "co2",
  },
  {
    id: "page-6",
    title: "Contact",
    slug: "contact",
    status: "published",
    authorId: "user-2",
    authorName: "Sarah Connor",
    template: "Contact Page with Form",
    createdAt: "2026-01-01T00:00:00Z",
    publishedAt: "2026-01-02T12:00:00Z",
    updatedAt: "2026-05-20T10:00:00Z",
    metaTitle: "Get in Touch - Contact Us | TechGadgets BD",
    metaDescription: "Contact TechGadgets BD. Reach out to our sales, support, or management teams for inquiries, quotes, or support tickets.",
    blocksCount: 5,
    companyId: "co2",
  },
  {
    id: "page-7",
    title: "Summer Promotion Landing Page",
    slug: "summer-deals-2026",
    status: "review",
    authorId: "user-3",
    authorName: "John Doe",
    template: "Landing Page Lead Gen",
    createdAt: "2026-06-15T09:00:00Z",
    updatedAt: "2026-06-19T11:00:00Z",
    metaTitle: "Exclusive Summer Tech Deals | TechGadgets BD",
    metaDescription: "Sign up now for early access to our massive summer gadgets promotion. Save up to 40% on top tech brands.",
    blocksCount: 9,
    companyId: "co2",
  },
  {
    id: "page-8",
    title: "Next-Gen Enterprise Solutions",
    slug: "enterprise-solutions-draft",
    status: "draft",
    authorId: "user-2",
    authorName: "Sarah Connor",
    template: "Homepage Corporate",
    createdAt: "2026-06-18T14:00:00Z",
    updatedAt: "2026-06-19T15:30:00Z",
    metaTitle: "Enterprise IT Solutions for Scale | TechGadgets BD",
    metaDescription: "Discover next-generation enterprise hardware and cloud hosting solutions custom-built for large-scale operations.",
    blocksCount: 3,
    companyId: "co2",
  },
];
