"use client";

import { useState, useMemo } from "react";
import {
  CheckCircle2, XCircle, AlertTriangle, Copy, Download,
  Upload, RotateCcw, Save, Play, ChevronDown, ChevronRight,
  Shield, Bot, FileText, Eye, Code2, Layers,
} from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem,
  DropdownMenuSeparator, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

/* ─── Default robots.txt content ──────────────────────────────────────────── */

const DEFAULT_ROBOTS = `# robots.txt for urbanwear.com
# Generated by MoharazNX SEO Manager

User-agent: *
Disallow: /admin/
Disallow: /checkout/
Disallow: /cart/
Disallow: /account/
Disallow: /api/
Disallow: /search?
Disallow: /?sort=
Disallow: /?filter=
Disallow: /cdn-cgi/
Allow: /

User-agent: Googlebot
Allow: /
Disallow: /admin/
Disallow: /checkout/
Crawl-delay: 1

User-agent: Bingbot
Allow: /
Disallow: /admin/
Crawl-delay: 2

User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

Sitemap: https://urbanwear.com/sitemap.xml
Sitemap: https://urbanwear.com/sitemap-products.xml
`;

/* ─── Presets ──────────────────────────────────────────────────────────────── */

const PRESETS: { label: string; description: string; content: string }[] = [
  {
    label: "Allow all (default)",
    description: "Let all bots crawl everything",
    content: `User-agent: *\nAllow: /\n\nSitemap: https://urbanwear.com/sitemap.xml\n`,
  },
  {
    label: "Block all bots",
    description: "Prevent all crawlers (staging sites)",
    content: `User-agent: *\nDisallow: /\n`,
  },
  {
    label: "E-commerce standard",
    description: "Block cart, checkout, account, search params",
    content: DEFAULT_ROBOTS,
  },
  {
    label: "Block SEO scrapers",
    description: "Block Ahrefs, Semrush, Moz, DotBot",
    content: `User-agent: *\nAllow: /\n\nUser-agent: AhrefsBot\nDisallow: /\n\nUser-agent: SemrushBot\nDisallow: /\n\nUser-agent: MJ12bot\nDisallow: /\n\nUser-agent: DotBot\nDisallow: /\n\nSitemap: https://urbanwear.com/sitemap.xml\n`,
  },
];

/* ─── Parser ───────────────────────────────────────────────────────────────── */

type ParsedGroup = {
  agents: string[];
  directives: { type: "allow" | "disallow" | "crawldelay" | "sitemap" | "comment" | "unknown"; value: string }[];
};

function parseRobots(text: string): { groups: ParsedGroup[]; sitemaps: string[]; errors: string[] } {
  const lines = text.split("\n");
  const groups: ParsedGroup[] = [];
  const sitemaps: string[] = [];
  const errors: string[] = [];
  let current: ParsedGroup | null = null;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const line = raw.trim();
    if (!line) { if (current) { groups.push(current); current = null; } continue; }
    if (line.startsWith("#")) continue;

    const [key, ...rest] = line.split(":");
    const val = rest.join(":").trim();
    const k = key.trim().toLowerCase();

    if (k === "user-agent") {
      if (!current) current = { agents: [], directives: [] };
      current.agents.push(val || "*");
    } else if (k === "allow") {
      if (!current) { errors.push(`Line ${i + 1}: Allow without User-agent`); continue; }
      current.directives.push({ type: "allow", value: val });
    } else if (k === "disallow") {
      if (!current) { errors.push(`Line ${i + 1}: Disallow without User-agent`); continue; }
      current.directives.push({ type: "disallow", value: val || "/" });
    } else if (k === "crawl-delay") {
      if (current) current.directives.push({ type: "crawldelay", value: val });
    } else if (k === "sitemap") {
      sitemaps.push(val);
    } else if (line !== "") {
      errors.push(`Line ${i + 1}: Unknown directive "${key.trim()}"`);
    }
  }
  if (current) groups.push(current);
  return { groups, sitemaps, errors };
}

/* ─── URL tester ───────────────────────────────────────────────────────────── */

function testUrl(parsed: ReturnType<typeof parseRobots>, url: string, agent = "*"): "allowed" | "blocked" | "unknown" {
  if (!url) return "unknown";
  const path = url.startsWith("http") ? new URL(url).pathname : url;
  const groups = parsed.groups.filter((g) =>
    g.agents.includes("*") || g.agents.some((a) => a.toLowerCase() === agent.toLowerCase()),
  );
  let result: "allowed" | "blocked" = "allowed";
  for (const g of groups) {
    for (const d of g.directives) {
      if (d.type !== "allow" && d.type !== "disallow") continue;
      const pat = d.value.replace(/\*/g, ".*");
      try {
        if (new RegExp(`^${pat}`).test(path)) {
          result = d.type === "allow" ? "allowed" : "blocked";
        }
      } catch {}
    }
  }
  return result;
}

/* ─── Subcomponents ────────────────────────────────────────────────────────── */

function DirectiveLine({ type, value }: { type: string; value: string }) {
  const config: Record<string, { color: string; icon: React.ReactNode; label: string }> = {
    allow:      { color: "text-emerald-600",  icon: <CheckCircle2 className="h-3.5 w-3.5" />, label: "Allow" },
    disallow:   { color: "text-red-500",      icon: <XCircle className="h-3.5 w-3.5" />,      label: "Disallow" },
    crawldelay: { color: "text-amber-500",    icon: <AlertTriangle className="h-3.5 w-3.5" />, label: "Crawl-delay" },
    sitemap:    { color: "text-blue-500",     icon: <FileText className="h-3.5 w-3.5" />,      label: "Sitemap" },
  };
  const c = config[type] ?? { color: "text-muted-foreground", icon: null, label: type };
  return (
    <div className={cn("flex items-center gap-2 py-0.5 text-[12px]", c.color)}>
      <span className="shrink-0">{c.icon}</span>
      <span className="font-medium w-20 shrink-0">{c.label}</span>
      <span className="font-mono text-foreground/80">{value || <em className="text-muted-foreground not-italic">empty (blocks all)</em>}</span>
    </div>
  );
}

function ParsedView({ parsed }: { parsed: ReturnType<typeof parseRobots> }) {
  const [collapsed, setCollapsed] = useState<Set<number>>(new Set());
  const toggle = (i: number) => setCollapsed((s) => { const n = new Set(s); n.has(i) ? n.delete(i) : n.add(i); return n; });

  return (
    <div className="flex flex-col gap-3">
      {parsed.errors.length > 0 && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 dark:border-amber-800 dark:bg-amber-950/20">
          <p className="mb-1 flex items-center gap-1.5 text-[11px] font-semibold text-amber-600">
            <AlertTriangle className="h-3.5 w-3.5" /> Parse warnings
          </p>
          {parsed.errors.map((e, i) => <p key={i} className="text-[11px] text-amber-600">{e}</p>)}
        </div>
      )}
      {parsed.groups.map((g, i) => (
        <div key={i} className="rounded-xl border border-input bg-muted/20 overflow-hidden">
          <button
            type="button"
            onClick={() => toggle(i)}
            className="flex w-full items-center gap-2 px-3 py-2 text-left hover:bg-muted/30 transition-colors"
          >
            {collapsed.has(i) ? <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" /> : <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />}
            <Bot className="h-3.5 w-3.5 text-muted-foreground" />
            <div className="flex flex-wrap gap-1">
              {g.agents.map((a) => (
                <span key={a} className={cn("rounded-full px-2 py-0.5 text-[10px] font-bold", a === "*" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground")}>
                  {a === "*" ? "All bots" : a}
                </span>
              ))}
            </div>
            <span className="ml-auto text-[10px] text-muted-foreground">{g.directives.length} rules</span>
          </button>
          {!collapsed.has(i) && (
            <div className="border-t border-input px-4 py-2">
              {g.directives.map((d, j) => <DirectiveLine key={j} type={d.type} value={d.value} />)}
            </div>
          )}
        </div>
      ))}
      {parsed.sitemaps.length > 0 && (
        <div className="rounded-xl border border-input bg-blue-50/50 px-4 py-3 dark:bg-blue-950/10">
          <p className="mb-1.5 flex items-center gap-1.5 text-[11px] font-semibold text-blue-600">
            <FileText className="h-3.5 w-3.5" /> Sitemaps declared
          </p>
          {parsed.sitemaps.map((s, i) => (
            <p key={i} className="font-mono text-[11px] text-blue-700 dark:text-blue-400">{s}</p>
          ))}
        </div>
      )}
    </div>
  );
}

/* ─── Main ─────────────────────────────────────────────────────────────────── */

export function RobotsEditor() {
  const [content, setContent] = useState(DEFAULT_ROBOTS);
  const [saved, setSaved] = useState(DEFAULT_ROBOTS);
  const [activeView, setActiveView] = useState<"split" | "editor" | "preview">("split");
  const [testUrl_, setTestUrl_] = useState("");
  const [testAgent, setTestAgent] = useState("*");

  const parsed = useMemo(() => parseRobots(content), [content]);
  const isDirty = content !== saved;

  const testResult = useMemo(() => testUrl(parsed, testUrl_, testAgent), [parsed, testUrl_, testAgent]);

  const handleSave = () => {
    setSaved(content);
    toast.success("robots.txt saved — prototype");
  };

  const handleReset = () => {
    setContent(saved);
    toast.info("Reset to last saved version");
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    toast.success("Copied to clipboard");
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "robots.txt";
    a.click();
    toast.success("Downloading robots.txt");
  };

  const lineCount = content.split("\n").length;
  const charCount = content.length;

  return (
    <div className="flex flex-col gap-4">
      {/* ── Toolbar ── */}
      <div className="flex flex-wrap items-center gap-2 rounded-xl border border-input bg-card px-3 py-2">
        {/* View toggle */}
        <div className="flex gap-0.5 rounded-lg border border-input bg-muted/30 p-0.5">
          {([
            { key: "editor",  icon: <Code2 className="h-3.5 w-3.5" />,   label: "Editor"  },
            { key: "split",   icon: <Layers className="h-3.5 w-3.5" />,  label: "Split"   },
            { key: "preview", icon: <Eye className="h-3.5 w-3.5" />,     label: "Preview" },
          ] as const).map((v) => (
            <button
              key={v.key}
              type="button"
              onClick={() => setActiveView(v.key)}
              className={cn(
                "flex items-center gap-1.5 rounded-md px-2.5 py-1 text-[11px] font-medium transition-colors",
                activeView === v.key ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground",
              )}
            >
              {v.icon} {v.label}
            </button>
          ))}
        </div>

        {/* Presets */}
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="sm" className="h-7 gap-1 text-xs">
              <Shield className="h-3.5 w-3.5" /> Presets <ChevronDown className="h-3 w-3 opacity-60" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" className="w-56">
            {PRESETS.map((p) => (
              <DropdownMenuItem key={p.label} onClick={() => { setContent(p.content); toast.info(`Loaded: ${p.label}`); }}>
                <div>
                  <p className="text-sm font-medium">{p.label}</p>
                  <p className="text-[11px] text-muted-foreground">{p.description}</p>
                </div>
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>

        <div className="ml-auto flex items-center gap-2">
          <span className="text-[10px] text-muted-foreground tabular-nums">{lineCount} lines · {charCount} chars</span>
          {isDirty && <span className="h-2 w-2 rounded-full bg-amber-400" title="Unsaved changes" />}
          <Button variant="ghost" size="sm" className="h-7 gap-1 text-xs" onClick={handleReset} disabled={!isDirty}>
            <RotateCcw className="h-3.5 w-3.5" /> Reset
          </Button>
          <Button variant="ghost" size="sm" className="h-7 gap-1 text-xs" onClick={handleCopy}>
            <Copy className="h-3.5 w-3.5" /> Copy
          </Button>
          <Button variant="ghost" size="sm" className="h-7 gap-1 text-xs" onClick={handleDownload}>
            <Download className="h-3.5 w-3.5" /> Download
          </Button>
          <Button size="sm" className="h-7 gap-1 text-xs" onClick={handleSave} disabled={!isDirty}>
            <Save className="h-3.5 w-3.5" /> {isDirty ? "Save changes" : "Saved"}
          </Button>
        </div>
      </div>

      {/* ── Editor + Preview ── */}
      <div className={cn("gap-4", activeView === "split" ? "grid lg:grid-cols-2" : "flex flex-col")}>
        {/* Editor */}
        {activeView !== "preview" && (
          <div className="flex flex-col gap-1.5">
            <p className="flex items-center gap-1.5 text-[11px] font-semibold text-muted-foreground uppercase tracking-wide">
              <Code2 className="h-3.5 w-3.5" /> Editor
              {isDirty && <span className="text-amber-500 font-normal normal-case">— unsaved changes</span>}
            </p>
            <div className="relative rounded-xl border border-input overflow-hidden bg-[#1e1e2e] dark:bg-[#13131a]">
              {/* Line numbers */}
              <div className="flex">
                <div className="select-none border-r border-white/10 bg-white/5 px-2 pt-3 text-right font-mono text-[11px] leading-5 text-white/30 min-w-[2.5rem]">
                  {content.split("\n").map((_, i) => (
                    <div key={i}>{i + 1}</div>
                  ))}
                </div>
                <textarea
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  spellCheck={false}
                  className="flex-1 resize-none bg-transparent p-3 font-mono text-[12px] leading-5 text-slate-100 outline-none placeholder:text-white/20 min-h-[420px]"
                  style={{ tabSize: 2 }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Preview */}
        {activeView !== "editor" && (
          <div className="flex flex-col gap-3">
            <p className="flex items-center gap-1.5 text-[11px] font-semibold text-muted-foreground uppercase tracking-wide">
              <Eye className="h-3.5 w-3.5" /> Parsed preview
              <span className="ml-1 rounded-full bg-muted px-1.5 py-0.5 text-[10px] font-normal normal-case">
                {parsed.groups.length} groups · {parsed.sitemaps.length} sitemaps
                {parsed.errors.length > 0 && ` · ${parsed.errors.length} warnings`}
              </span>
            </p>

            {/* URL Tester */}
            <div className="rounded-xl border border-input bg-card p-3">
              <p className="mb-2 flex items-center gap-1.5 text-[11px] font-semibold text-muted-foreground">
                <Play className="h-3.5 w-3.5" /> URL Tester
              </p>
              <div className="flex gap-2">
                <Input
                  placeholder="e.g. /checkout/ or https://urbanwear.com/admin/"
                  value={testUrl_}
                  onChange={(e) => setTestUrl_(e.target.value)}
                  className="h-8 flex-1 font-mono text-xs"
                />
                <select
                  value={testAgent}
                  onChange={(e) => setTestAgent(e.target.value)}
                  className="h-8 rounded-md border border-input bg-background px-2 text-xs"
                >
                  <option value="*">All bots</option>
                  <option value="Googlebot">Googlebot</option>
                  <option value="Bingbot">Bingbot</option>
                  <option value="AhrefsBot">AhrefsBot</option>
                </select>
              </div>
              {testUrl_ && (
                <div className={cn(
                  "mt-2 flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium",
                  testResult === "allowed"  && "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-400",
                  testResult === "blocked"  && "bg-red-50 text-red-600 dark:bg-red-950/20 dark:text-red-400",
                  testResult === "unknown"  && "bg-muted text-muted-foreground",
                )}>
                  {testResult === "allowed" && <CheckCircle2 className="h-4 w-4" />}
                  {testResult === "blocked"  && <XCircle className="h-4 w-4" />}
                  {testResult === "allowed" && "Allowed — this URL can be crawled"}
                  {testResult === "blocked"  && "Blocked — this URL will not be crawled"}
                </div>
              )}
            </div>

            <ParsedView parsed={parsed} />
          </div>
        )}
      </div>

      {/* ── Bottom info bar ── */}
      <div className="flex flex-wrap items-center gap-4 rounded-xl border border-input bg-muted/20 px-4 py-2.5 text-[11px] text-muted-foreground">
        <span className="flex items-center gap-1.5">
          <FileText className="h-3.5 w-3.5" />
          Live at <span className="font-mono text-foreground">https://urbanwear.com/robots.txt</span>
        </span>
        <span>Last modified: <span className="text-foreground">2026-06-18 14:22</span></span>
        <span>Last crawled by Google: <span className="text-foreground">2026-06-20 08:11</span></span>
        <a
          href="https://search.google.com/search-console"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-auto text-blue-500 underline underline-offset-2 hover:text-blue-600"
          onClick={(e) => e.preventDefault()}
        >
          Test in Google Search Console ↗
        </a>
      </div>
    </div>
  );
}
