import type { LucideIcon } from "lucide-react";
import {
  Box,
  CircuitBoard,
  Cpu,
  Disc,
  Fan,
  Gamepad2,
  HardDrive,
  Headphones,
  Keyboard,
  MemoryStick,
  Mic,
  Monitor,
  MonitorSmartphone,
  Mouse,
  RectangleHorizontal,
  Speaker,
  Video,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { PcBuilderStepId } from "@/lib/builder/types";

export const PC_BUILDER_STEP_ICONS: Record<PcBuilderStepId, LucideIcon> = {
  cpu: Cpu,
  motherboard: CircuitBoard,
  ram: MemoryStick,
  gpu: Gamepad2,
  ssd: HardDrive,
  hdd: Disc,
  psu: Zap,
  case: Box,
  cooler: Fan,
  os: MonitorSmartphone,
  case_fans: Fan,
  wifi: Wifi,
  accessories: Wrench,
  monitor: Monitor,
  mouse: Mouse,
  keyboard: Keyboard,
  mousepad: RectangleHorizontal,
  controller: Gamepad2,
  headset: Headphones,
  microphone: Mic,
  speakers: Speaker,
  webcam: Video,
};
