AI_AGENT_SEED = [
    {
        "id": "catalog_agent",
        "name": "Catalog Agent",
        "domain": "Product Master",
        "status": "active",
        "tools": 12,
        "runs_today": 48,
        "model": "gpt-4o-mini",
        "description": "Product copy, tags, attributes, publish proposals",
    },
    {
        "id": "inventory_agent",
        "name": "Inventory Agent",
        "domain": "Inventory",
        "status": "active",
        "tools": 8,
        "runs_today": 22,
        "model": "gpt-4o-mini",
        "description": "Forecast, reorder, adjustment proposals",
    },
    {
        "id": "purchase_agent",
        "name": "Purchase Agent",
        "domain": "Purchase",
        "status": "idle",
        "tools": 6,
        "runs_today": 5,
        "model": "claude-sonnet",
        "description": "RFQ draft, PO suggest, vendor match",
    },
    {
        "id": "sales_agent",
        "name": "Sales Agent",
        "domain": "Sales",
        "status": "active",
        "tools": 9,
        "runs_today": 15,
        "model": "gpt-4o",
        "description": "Quote draft, discount suggest, follow-up",
    },
    {
        "id": "crm_agent",
        "name": "CRM Agent",
        "domain": "CRM",
        "status": "active",
        "tools": 10,
        "runs_today": 19,
        "model": "gpt-4o-mini",
        "description": "Lead score, churn, next-best-action",
    },
    {
        "id": "marketing_agent",
        "name": "Marketing Agent",
        "domain": "Marketing",
        "status": "active",
        "tools": 11,
        "runs_today": 31,
        "model": "gpt-4o",
        "description": "Campaign suggest, segments, content draft",
    },
    {
        "id": "seo_agent",
        "name": "SEO Agent",
        "domain": "SEO",
        "status": "active",
        "tools": 8,
        "runs_today": 28,
        "model": "gpt-4o-mini",
        "description": "Meta, schema, audit, keyword suggest",
    },
    {
        "id": "support_agent",
        "name": "Support Agent",
        "domain": "Helpdesk",
        "status": "idle",
        "tools": 7,
        "runs_today": 8,
        "model": "claude-haiku",
        "description": "Ticket summarize, KB suggest, reply draft",
    },
    {
        "id": "developer_agent",
        "name": "Developer Agent",
        "domain": "Platform",
        "status": "disabled",
        "tools": 5,
        "runs_today": 0,
        "model": "—",
        "description": "Schema read, doc RAG, migration plan",
    },
    {
        "id": "analytics_agent",
        "name": "Analytics Agent",
        "domain": "Analytics",
        "status": "active",
        "tools": 6,
        "runs_today": 42,
        "model": "gpt-4o",
        "description": "Reports, forecasts, anomaly narrative",
    },
]
