from datetime import datetime

AI_AUDIT_LOG_SEED = [
    {
        "id": "log_001",
        "action": "ai.action.proposed",
        "agent": "Catalog Agent",
        "user": "admin@urbanwear.bd",
        "summary": "Proposed price update for prod_0042",
        "tokens": 1840,
        "logged_at": datetime(2026, 6, 15, 10, 42, 18),
    },
    {
        "id": "log_002",
        "action": "ai.task.completed",
        "agent": "SEO Agent",
        "user": "manager@urbanwear.bd",
        "summary": "Generated meta for 12 category pages",
        "tokens": 6200,
        "logged_at": datetime(2026, 6, 15, 10, 15, 3),
    },
    {
        "id": "log_003",
        "action": "ai.action.executed",
        "agent": "Marketing Agent",
        "user": "admin@urbanwear.bd",
        "summary": "Applied campaign draft to Summer Sale",
        "tokens": 3100,
        "logged_at": datetime(2026, 6, 15, 9, 48, 44),
    },
    {
        "id": "log_004",
        "action": "ai.action.rejected",
        "agent": "Inventory Agent",
        "user": "ops@urbanwear.bd",
        "summary": "Rejected reorder proposal — budget cap",
        "tokens": 920,
        "logged_at": datetime(2026, 6, 15, 9, 22, 11),
    },
    {
        "id": "log_005",
        "action": "ai.budget.alert",
        "agent": "Chief Agent",
        "user": "system",
        "summary": "Token budget reached 60% for June",
        "tokens": 0,
        "logged_at": datetime(2026, 6, 15, 8, 0, 0),
    },
    {
        "id": "log_006",
        "action": "ai.action.proposed",
        "agent": "Sales Agent",
        "user": "sales@urbanwear.bd",
        "summary": "Suggested 8% discount on bulk order ORD-1042",
        "tokens": 2100,
        "logged_at": datetime(2026, 6, 14, 17, 55, 30),
    },
    {
        "id": "log_007",
        "action": "ai.task.completed",
        "agent": "Catalog Agent",
        "user": "admin@urbanwear.bd",
        "summary": "Bulk tag refresh for 24 summer SKUs",
        "tokens": 142000,
        "logged_at": datetime(2026, 6, 16, 11, 20, 0),
    },
    {
        "id": "log_008",
        "action": "ai.task.completed",
        "agent": "Analytics Agent",
        "user": "manager@urbanwear.bd",
        "summary": "Weekly sales digest generated",
        "tokens": 168000,
        "logged_at": datetime(2026, 6, 17, 9, 5, 0),
    },
    {
        "id": "log_009",
        "action": "ai.action.executed",
        "agent": "Marketing Agent",
        "user": "admin@urbanwear.bd",
        "summary": "Scheduled abandoned-cart email sequence",
        "tokens": 155000,
        "logged_at": datetime(2026, 6, 18, 14, 30, 0),
    },
    {
        "id": "log_010",
        "action": "ai.task.completed",
        "agent": "SEO Agent",
        "user": "manager@urbanwear.bd",
        "summary": "Schema markup pass for top 40 PDPs",
        "tokens": 201000,
        "logged_at": datetime(2026, 6, 19, 10, 0, 0),
    },
    {
        "id": "log_011",
        "action": "ai.action.proposed",
        "agent": "Inventory Agent",
        "user": "ops@urbanwear.bd",
        "summary": "Safety stock adjustment for 6 SKUs",
        "tokens": 178000,
        "logged_at": datetime(2026, 6, 20, 16, 45, 0),
    },
    {
        "id": "log_012",
        "action": "ai.task.completed",
        "agent": "Catalog Agent",
        "user": "admin@urbanwear.bd",
        "summary": "Weekend flash-sale copy variants",
        "tokens": 92000,
        "logged_at": datetime(2026, 6, 21, 12, 10, 0),
    },
    {
        "id": "log_013",
        "action": "ai.task.completed",
        "agent": "Sales Agent",
        "user": "sales@urbanwear.bd",
        "summary": "Quote follow-up drafts for 8 open deals",
        "tokens": 104000,
        "logged_at": datetime(2026, 6, 22, 8, 30, 0),
    },
]
