AI_TOOL_SEED = [
    {
        "id": "product_description",
        "name": "Product Description",
        "agent": "Catalog",
        "category": "Catalog",
        "risk": "low",
        "description": "Generate rich product descriptions from bullet points",
    },
    {
        "id": "blog_writer",
        "name": "Blog Writer",
        "agent": "Marketing",
        "category": "Content",
        "risk": "low",
        "description": "Draft blog posts from topic and tone",
    },
    {
        "id": "seo_generator",
        "name": "SEO Generator",
        "agent": "SEO",
        "category": "SEO",
        "risk": "low",
        "description": "Full SEO content optimization suggestions",
    },
    {
        "id": "meta_generator",
        "name": "Meta Generator",
        "agent": "SEO",
        "category": "SEO",
        "risk": "low",
        "description": "Title, description, keywords for any URL",
    },
    {
        "id": "product_tags",
        "name": "Product Tags",
        "agent": "Catalog",
        "category": "Catalog",
        "risk": "low",
        "description": "Auto-tag products for search and filters",
    },
    {
        "id": "review_summary",
        "name": "Review Summary",
        "agent": "Catalog",
        "category": "Catalog",
        "risk": "low",
        "description": "Summarize customer reviews and sentiment",
    },
    {
        "id": "customer_support",
        "name": "Customer Support",
        "agent": "Support",
        "category": "Support",
        "risk": "medium",
        "description": "Draft replies and suggest KB articles",
    },
    {
        "id": "translation",
        "name": "Translation",
        "agent": "Catalog",
        "category": "Content",
        "risk": "low",
        "description": "Translate product content to Bengali or English",
    },
    {
        "id": "image_generation",
        "name": "Image Generation",
        "agent": "Marketing",
        "category": "Creative",
        "risk": "medium",
        "description": "Generate product lifestyle images",
    },
    {
        "id": "banner_generator",
        "name": "Banner Generator",
        "agent": "Marketing",
        "category": "Creative",
        "risk": "low",
        "description": "Campaign banners for web and social",
    },
    {
        "id": "sales_forecast",
        "name": "Sales Forecast",
        "agent": "Analytics",
        "category": "Analytics",
        "risk": "low",
        "description": "Revenue and order volume projections",
    },
    {
        "id": "inventory_forecast",
        "name": "Inventory Forecast",
        "agent": "Inventory",
        "category": "Analytics",
        "risk": "medium",
        "description": "Stock-out risk and reorder recommendations",
    },
    {
        "id": "product_recommendation",
        "name": "Product Recommendation",
        "agent": "Analytics",
        "category": "Merchandising",
        "risk": "low",
        "description": "Cross-sell and upsell suggestions",
    },
]
