"""Seed payloads for commerce_customers — mirrors admin mock customers."""

from __future__ import annotations

from datetime import date
from decimal import Decimal

CUSTOMER_SEED: list[dict] = [
    {
        "id": "cust_001",
        "customer_code": "C-10001",
        "name": "Rakibul Hasan",
        "phone": "01711-234567",
        "email": "rakib@example.com",
        "group": "retail",
        "status": "active",
        "loyalty_tier": "gold",
        "city": "Dhaka",
        "region": "Dhaka Division",
        "country": "Bangladesh",
        "customer_since": date(2022, 3, 15),
        "last_order_date": date(2026, 6, 10),
        "assigned_staff": "Sumaiya Akter",
        "tags": ["loyal", "tech-buyer"],
        "total_orders": 18,
        "total_spend": Decimal("145200.00"),
        "avg_order_value": Decimal("8067.00"),
        "return_rate": Decimal("5.60"),
        "reward_points": 1450,
        "wallet_balance": Decimal("500.00"),
        "risk_score": 12,
        "risk_level": "low",
        "addresses": [
            {"id": "addr_001", "label": "Home", "address": "42/B, Mirpur-10", "city": "Dhaka", "region": "Dhaka Division", "country": "Bangladesh", "isDefault": True},
        ],
        "timeline": [
            {"id": "tl_001", "type": "order", "title": "Order #ORD-1001 delivered", "actor": "System", "at": "2026-06-10T11:00:00Z"},
            {"id": "tl_005", "type": "registered", "title": "Customer registered", "actor": "System", "at": "2022-03-15T08:00:00Z"},
        ],
        "comments": [
            {"id": "cm_001", "author": "Sumaiya Akter", "authorInitials": "SA", "body": "Customer prefers afternoon deliveries.", "isInternal": True, "at": "2026-06-08T09:35:00Z"},
        ],
        "ai_insights": {
            "summary": "High-value retail customer with consistent purchase history.",
            "purchaseSummary": "18 orders totaling ৳1,45,200.",
            "churnRisk": "low",
            "churnScore": 12,
            "churnReasons": [],
            "retentionProbability": 88,
            "predictedLtv": 280000,
            "favoriteCategories": ["Laptops", "Accessories"],
            "favoriteBrands": ["Dell", "Logitech"],
            "recommendedProducts": [{"name": "Dell UltraSharp 27\" Monitor", "reason": "Similar customer pattern"}],
            "marketingSuggestions": ["Send Platinum tier upgrade offer"],
        },
    },
    {
        "id": "cust_002",
        "customer_code": "C-10002",
        "name": "Fatema Begum",
        "phone": "01812-345678",
        "email": "fatema@example.com",
        "group": "wholesale",
        "status": "vip",
        "loyalty_tier": "platinum",
        "city": "Chittagong",
        "region": "Chittagong Division",
        "country": "Bangladesh",
        "customer_since": date(2021, 8, 1),
        "last_order_date": date(2026, 6, 5),
        "assigned_staff": "Rafiq Ahmed",
        "tags": ["vip", "wholesale"],
        "total_orders": 54,
        "total_spend": Decimal("892000.00"),
        "avg_order_value": Decimal("16519.00"),
        "return_rate": Decimal("2.10"),
        "reward_points": 8920,
        "wallet_balance": Decimal("3200.00"),
        "risk_score": 8,
        "risk_level": "low",
        "addresses": [
            {"id": "addr_010", "label": "Warehouse", "address": "Plot 15, CEPZ", "city": "Chittagong", "region": "Chittagong Division", "country": "Bangladesh", "isDefault": True},
        ],
        "timeline": [
            {"id": "tl_010", "type": "order", "title": "Order #ORD-2001 placed", "actor": "System", "at": "2026-06-05T10:00:00Z"},
        ],
        "comments": [
            {"id": "cm_010", "author": "Rafiq Ahmed", "authorInitials": "RA", "body": "Key wholesale account.", "isInternal": True, "at": "2026-05-20T10:00:00Z"},
        ],
        "ai_insights": {
            "summary": "High-volume Platinum wholesale customer.",
            "purchaseSummary": "54 orders totaling ৳8,92,000.",
            "churnRisk": "low",
            "churnScore": 8,
            "churnReasons": [],
            "retentionProbability": 94,
            "predictedLtv": 2500000,
            "favoriteCategories": ["Laptops", "Smartphones"],
            "favoriteBrands": ["Samsung", "Apple"],
            "recommendedProducts": [{"name": "Samsung Galaxy A55 (Bulk)", "reason": "Wholesale pattern"}],
            "marketingSuggestions": ["Propose Q3 bulk discount agreement"],
        },
    },
    {
        "id": "cust_003",
        "customer_code": "C-10003",
        "name": "Imran Hossain",
        "phone": "01913-456789",
        "email": "imran@example.com",
        "group": "retail",
        "status": "inactive",
        "loyalty_tier": "silver",
        "city": "Sylhet",
        "region": "Sylhet Division",
        "country": "Bangladesh",
        "customer_since": date(2023, 1, 20),
        "last_order_date": date(2025, 11, 2),
        "assigned_staff": "Karim Ahmed",
        "tags": ["at-risk"],
        "total_orders": 4,
        "total_spend": Decimal("28600.00"),
        "avg_order_value": Decimal("7150.00"),
        "return_rate": Decimal("12.50"),
        "reward_points": 180,
        "wallet_balance": Decimal("0.00"),
        "risk_score": 68,
        "risk_level": "high",
        "addresses": [
            {"id": "addr_020", "label": "Home", "address": "Zindabazar", "city": "Sylhet", "region": "Sylhet Division", "country": "Bangladesh", "isDefault": True},
        ],
        "timeline": [
            {"id": "tl_020", "type": "status_change", "title": "Marked inactive — no orders in 7 months", "actor": "System", "at": "2026-05-01T00:00:00Z"},
        ],
        "comments": [],
        "ai_insights": {
            "summary": "At-risk customer — long inactivity window.",
            "purchaseSummary": "4 orders totaling ৳28,600.",
            "churnRisk": "high",
            "churnScore": 68,
            "churnReasons": ["No order in 7+ months", "High return rate"],
            "retentionProbability": 32,
            "predictedLtv": 45000,
            "favoriteCategories": ["Smartphones"],
            "favoriteBrands": ["Samsung"],
            "recommendedProducts": [{"name": "Samsung Galaxy A35", "reason": "Win-back category match"}],
            "marketingSuggestions": ["Send 15% discount win-back coupon"],
        },
    },
    {
        "id": "cust_004",
        "customer_code": "C-10004",
        "name": "Nasrin Akter",
        "phone": "01615-567890",
        "email": "nasrin@example.com",
        "group": "corporate",
        "status": "active",
        "loyalty_tier": "gold",
        "city": "Dhaka",
        "region": "Dhaka Division",
        "country": "Bangladesh",
        "customer_since": date(2022, 7, 10),
        "last_order_date": date(2026, 6, 8),
        "assigned_staff": "Sumaiya Akter",
        "tags": ["corporate", "bulk-buyer"],
        "total_orders": 22,
        "total_spend": Decimal("320000.00"),
        "avg_order_value": Decimal("14545.00"),
        "return_rate": Decimal("3.00"),
        "reward_points": 3200,
        "wallet_balance": Decimal("1200.00"),
        "risk_score": 18,
        "risk_level": "low",
        "addresses": [
            {"id": "addr_030", "label": "Office", "address": "Bashundhara City, 5th Floor", "city": "Dhaka", "region": "Dhaka Division", "country": "Bangladesh", "isDefault": True},
        ],
        "timeline": [
            {"id": "tl_030", "type": "order", "title": "Order #ORD-4001 confirmed", "actor": "System", "at": "2026-06-08T09:00:00Z"},
        ],
        "comments": [
            {"id": "cm_030", "author": "Sumaiya Akter", "authorInitials": "SA", "body": "Corporate account — Net-30 terms.", "isInternal": True, "at": "2022-08-01T09:00:00Z"},
        ],
        "ai_insights": {
            "summary": "Corporate IT procurement contact with steady bulk orders.",
            "purchaseSummary": "22 orders totaling ৳3,20,000.",
            "churnRisk": "low",
            "churnScore": 18,
            "churnReasons": [],
            "retentionProbability": 85,
            "predictedLtv": 800000,
            "favoriteCategories": ["Laptops", "Networking"],
            "favoriteBrands": ["HP", "Dell"],
            "recommendedProducts": [{"name": "HP LaserJet Pro Bundle", "reason": "Office upgrade cycle"}],
            "marketingSuggestions": ["Propose annual procurement agreement"],
        },
    },
    {
        "id": "cust_005",
        "customer_code": "C-10005",
        "name": "Tanvir Ahmed",
        "phone": "01714-678901",
        "email": "tanvir@example.com",
        "group": "retail",
        "status": "active",
        "loyalty_tier": "silver",
        "city": "Rajshahi",
        "region": "Rajshahi Division",
        "country": "Bangladesh",
        "customer_since": date(2024, 2, 14),
        "last_order_date": date(2026, 6, 11),
        "assigned_staff": None,
        "tags": ["new", "mobile-buyer"],
        "total_orders": 3,
        "total_spend": Decimal("22400.00"),
        "avg_order_value": Decimal("7467.00"),
        "return_rate": Decimal("0.00"),
        "reward_points": 224,
        "wallet_balance": Decimal("0.00"),
        "risk_score": 35,
        "risk_level": "medium",
        "addresses": [
            {"id": "addr_040", "label": "Home", "address": "23, Shaheb Bazar", "city": "Rajshahi", "region": "Rajshahi Division", "country": "Bangladesh", "isDefault": True},
        ],
        "timeline": [
            {"id": "tl_040", "type": "order", "title": "Order #ORD-5001 shipped", "actor": "System", "at": "2026-06-11T12:00:00Z"},
        ],
        "comments": [],
        "ai_insights": {
            "summary": "New mobile-first buyer with growing engagement.",
            "purchaseSummary": "3 orders totaling ৳22,400.",
            "churnRisk": "medium",
            "churnScore": 35,
            "churnReasons": ["Limited order history"],
            "retentionProbability": 62,
            "predictedLtv": 95000,
            "favoriteCategories": ["Smartphones", "Accessories"],
            "favoriteBrands": ["Xiaomi", "Samsung"],
            "recommendedProducts": [{"name": "Phone case bundle", "reason": "Accessory attach rate"}],
            "marketingSuggestions": ["Welcome series with mobile accessories"],
        },
    },
]
