from __future__ import annotations

META_SEED: list[dict] = [
    {"id": "meta_001", "entity_type": "product", "title": "ASUS TUF Gaming F15", "url": "/asus-tuf-gaming-f15", "meta_title": "ASUS TUF Gaming F15 — MoharazNX", "meta_description": "Buy ASUS TUF Gaming F15 laptop in Bangladesh. RTX graphics, fast delivery.", "og_image": "https://picsum.photos/seed/asus-f15/1200/630", "schema_type": "Product", "score": 92, "issues": []},
    {"id": "meta_002", "entity_type": "product", "title": "Dell Inspiron 15", "url": "/dell-inspiron-15", "meta_title": "", "meta_description": "Dell Inspiron 15 laptop.", "schema_type": "Product", "score": 48, "issues": ["Missing meta title", "Description too short", "Missing OG image"]},
    {"id": "meta_003", "entity_type": "category", "title": "Laptops", "url": "/laptops", "meta_title": "Laptops — Shop Online | MoharazNX", "meta_description": "", "og_image": "https://picsum.photos/seed/laptops/1200/630", "schema_type": "Category", "score": 62, "issues": ["Missing meta description"]},
    {"id": "meta_004", "entity_type": "product", "title": "Logitech MX Master 3", "url": "/logitech-mx-master-3", "meta_title": "Logitech MX Master 3 | MoharazNX", "meta_description": "Logitech MX Master 3 | MoharazNX", "schema_type": "Product", "score": 55, "issues": ["Duplicate description pattern", "Missing OG image"]},
    {"id": "meta_005", "entity_type": "brand", "title": "ASUS", "url": "/brands/asus", "meta_title": "ASUS — Shop at MoharazNX", "meta_description": "Official ASUS laptops, monitors, and components in Bangladesh.", "og_image": "https://picsum.photos/seed/asus-brand/1200/630", "schema_type": "WebPage", "score": 88, "issues": []},
    {"id": "meta_006", "entity_type": "page", "title": "About Us", "url": "/about", "meta_title": "About MoharazNX", "meta_description": "Learn about MoharazNX.", "schema_type": "WebPage", "score": 40, "issues": ["Description too short", "Missing OG image"]},
    {"id": "meta_007", "entity_type": "product", "title": "Samsung 27\" Monitor", "url": "/samsung-27-monitor", "meta_title": "Samsung 27\" Monitor — MoharazNX", "meta_description": "4K Samsung monitor with HDR10. Best price in Dhaka.", "og_image": "https://picsum.photos/seed/samsung-mon/1200/630", "schema_type": "Product", "score": 95, "issues": []},
    {"id": "meta_008", "entity_type": "category", "title": "Monitors", "url": "/monitors", "meta_title": "Monitors — MoharazNX", "meta_description": "Shop gaming and office monitors from top brands.", "og_image": "https://picsum.photos/seed/monitors/1200/630", "schema_type": "Category", "score": 78, "issues": []},
]
