#!/usr/bin/env python3
"""Seed MoharazNX catalog_products — computer-store style (BDT)."""

from decimal import Decimal

from app.database import SessionLocal
from app.models.catalog_product import CatalogProduct

CATALOG_SEED: list[dict] = [
    {
        "name": "ASUS TUF Gaming F15",
        "slug": "asus-tuf-gaming-f15",
        "sku": "SKU-ASUS-F15",
        "price": Decimal("89999.00"),
        "stock": 12,
        "status": "published",
        "brand": "ASUS",
        "category": "Laptops",
        "thumbnail": "https://picsum.photos/seed/asus-f15/80/80",
    },
    {
        "name": "Dell Inspiron 15",
        "slug": "dell-inspiron-15",
        "sku": "SKU-DELL-15",
        "price": Decimal("64999.00"),
        "stock": 8,
        "status": "published",
        "brand": "Dell",
        "category": "Laptops",
        "thumbnail": "https://picsum.photos/seed/dell-15/80/80",
    },
    {
        "name": "HP Pavilion 14",
        "slug": "hp-pavilion-14",
        "sku": "SKU-HP-P14",
        "price": Decimal("58999.00"),
        "stock": 15,
        "status": "published",
        "brand": "HP",
        "category": "Laptops",
        "thumbnail": "https://picsum.photos/seed/hp-p14/80/80",
    },
    {
        "name": "Lenovo IdeaPad Slim 5",
        "slug": "lenovo-ideapad-slim-5",
        "sku": "SKU-LNV-SL5",
        "price": Decimal("72999.00"),
        "stock": 6,
        "status": "published",
        "brand": "Lenovo",
        "category": "Laptops",
        "thumbnail": "https://picsum.photos/seed/lenovo-sl5/80/80",
    },
    {
        "name": "MacBook Air M2",
        "slug": "macbook-air-m2",
        "sku": "SKU-APL-MBA2",
        "price": Decimal("134999.00"),
        "stock": 4,
        "status": "published",
        "brand": "Apple",
        "category": "Laptops",
        "thumbnail": "https://picsum.photos/seed/mba-m2/80/80",
    },
    {
        "name": "Logitech MX Master 3S",
        "slug": "logitech-mx-master-3s",
        "sku": "SKU-LOGI-MX3S",
        "price": Decimal("8990.00"),
        "stock": 45,
        "status": "published",
        "brand": "Logitech",
        "category": "Accessories",
        "thumbnail": "https://picsum.photos/seed/logi-mx/80/80",
    },
    {
        "name": "Razer DeathAdder V3",
        "slug": "razer-deathadder-v3",
        "sku": "SKU-RZR-DA3",
        "price": Decimal("7490.00"),
        "stock": 30,
        "status": "published",
        "brand": "Razer",
        "category": "Accessories",
        "thumbnail": "https://picsum.photos/seed/razer-da3/80/80",
    },
    {
        "name": "Samsung 27\" Odyssey G5",
        "slug": "samsung-odyssey-g5-27",
        "sku": "SKU-SAM-G527",
        "price": Decimal("32999.00"),
        "stock": 10,
        "status": "published",
        "brand": "Samsung",
        "category": "Monitors",
        "thumbnail": "https://picsum.photos/seed/sam-g5/80/80",
    },
    {
        "name": "LG UltraWide 34WP65C",
        "slug": "lg-ultrawide-34wp65c",
        "sku": "SKU-LG-UW34",
        "price": Decimal("45999.00"),
        "stock": 7,
        "status": "published",
        "brand": "LG",
        "category": "Monitors",
        "thumbnail": "https://picsum.photos/seed/lg-uw/80/80",
    },
    {
        "name": "Intel Core i7-14700K",
        "slug": "intel-core-i7-14700k",
        "sku": "SKU-INT-14700K",
        "price": Decimal("42999.00"),
        "stock": 18,
        "status": "published",
        "brand": "Intel",
        "category": "Components",
        "thumbnail": "https://picsum.photos/seed/intel-i7/80/80",
    },
    {
        "name": "AMD Ryzen 7 7800X3D",
        "slug": "amd-ryzen-7-7800x3d",
        "sku": "SKU-AMD-7800X3D",
        "price": Decimal("38999.00"),
        "stock": 14,
        "status": "published",
        "brand": "AMD",
        "category": "Components",
        "thumbnail": "https://picsum.photos/seed/amd-r7/80/80",
    },
    {
        "name": "Corsair Vengeance 32GB DDR5",
        "slug": "corsair-vengeance-32gb-ddr5",
        "sku": "SKU-COR-DDR5-32",
        "price": Decimal("11999.00"),
        "stock": 25,
        "status": "published",
        "brand": "Corsair",
        "category": "Components",
        "thumbnail": "https://picsum.photos/seed/corsair-ram/80/80",
    },
    {
        "name": "Samsung 990 Pro 1TB NVMe",
        "slug": "samsung-990-pro-1tb",
        "sku": "SKU-SAM-990P1T",
        "price": Decimal("14999.00"),
        "stock": 22,
        "status": "published",
        "brand": "Samsung",
        "category": "Storage",
        "thumbnail": "https://picsum.photos/seed/sam-990/80/80",
    },
    {
        "name": "ASUS ROG Strix RTX 4070",
        "slug": "asus-rog-strix-rtx-4070",
        "sku": "SKU-ASUS-4070",
        "price": Decimal("89999.00"),
        "stock": 5,
        "status": "published",
        "brand": "ASUS",
        "category": "Components",
        "thumbnail": "https://picsum.photos/seed/asus-4070/80/80",
    },
    {
        "name": "Keychron K2 Pro",
        "slug": "keychron-k2-pro",
        "sku": "SKU-KEY-K2P",
        "price": Decimal("12999.00"),
        "stock": 20,
        "status": "published",
        "brand": "Keychron",
        "category": "Accessories",
        "thumbnail": "https://picsum.photos/seed/keychron/80/80",
    },
    {
        "name": "Sony WH-1000XM5",
        "slug": "sony-wh-1000xm5",
        "sku": "SKU-SNY-XM5",
        "price": Decimal("34999.00"),
        "stock": 11,
        "status": "published",
        "brand": "Sony",
        "category": "Audio",
        "thumbnail": "https://picsum.photos/seed/sony-xm5/80/80",
    },
    {
        "name": "TP-Link Archer AX73",
        "slug": "tp-link-archer-ax73",
        "sku": "SKU-TPL-AX73",
        "price": Decimal("8999.00"),
        "stock": 35,
        "status": "published",
        "brand": "TP-Link",
        "category": "Networking",
        "thumbnail": "https://picsum.photos/seed/tplink/80/80",
    },
    {
        "name": "Canon PIXMA G3730",
        "slug": "canon-pixma-g3730",
        "sku": "SKU-CAN-G3730",
        "price": Decimal("18999.00"),
        "stock": 9,
        "status": "draft",
        "brand": "Canon",
        "category": "Printers",
        "thumbnail": "https://picsum.photos/seed/canon-g3730/80/80",
    },
    {
        "name": "Xiaomi Redmi Pad SE",
        "slug": "xiaomi-redmi-pad-se",
        "sku": "SKU-XMI-PADSE",
        "price": Decimal("22999.00"),
        "stock": 16,
        "status": "published",
        "brand": "Xiaomi",
        "category": "Tablets",
        "thumbnail": "https://picsum.photos/seed/xiaomi-pad/80/80",
    },
    {
        "name": "Anker 737 Power Bank",
        "slug": "anker-737-power-bank",
        "sku": "SKU-ANK-737",
        "price": Decimal("9990.00"),
        "stock": 40,
        "status": "published",
        "brand": "Anker",
        "category": "Accessories",
        "thumbnail": "https://picsum.photos/seed/anker-737/80/80",
    },
]

# Parents must appear before children (parent_slug resolved at seed time).
CATEGORY_SEED: list[dict] = [
    {
        "slug": "computers",
        "name": "Computers",
        "caption": "Computers",
        "parent_slug": None,
        "sort_order": 0,
        "is_active": True,
        "show_in_top_menu": True,
        "description": "Desktops, laptops, and tablets.",
        "icon_url": "https://picsum.photos/seed/cat-computers/64/64",
    },
    {
        "slug": "laptops",
        "name": "Laptops",
        "caption": "Laptops",
        "parent_slug": "computers",
        "sort_order": 0,
        "is_active": True,
        "show_in_top_menu": True,
        "icon_url": "https://picsum.photos/seed/cat-laptops/64/64",
    },
    {
        "slug": "tablets",
        "name": "Tablets",
        "caption": "Tablets",
        "parent_slug": "computers",
        "sort_order": 1,
        "is_active": True,
        "show_in_top_menu": False,
    },
    {
        "slug": "peripherals",
        "name": "Peripherals",
        "caption": "Peripherals",
        "parent_slug": None,
        "sort_order": 1,
        "is_active": True,
        "show_in_top_menu": True,
    },
    {
        "slug": "monitors",
        "name": "Monitors",
        "caption": "Monitors",
        "parent_slug": "peripherals",
        "sort_order": 0,
        "is_active": True,
        "show_in_top_menu": False,
    },
    {
        "slug": "accessories",
        "name": "Accessories",
        "caption": "Accessories",
        "parent_slug": "peripherals",
        "sort_order": 1,
        "is_active": True,
        "show_in_top_menu": True,
    },
    {
        "slug": "audio",
        "name": "Audio",
        "caption": "Audio",
        "parent_slug": "peripherals",
        "sort_order": 2,
        "is_active": True,
        "show_in_top_menu": False,
    },
    {
        "slug": "printers",
        "name": "Printers",
        "caption": "Printers",
        "parent_slug": "peripherals",
        "sort_order": 3,
        "is_active": True,
        "show_in_top_menu": False,
    },
    {
        "slug": "components",
        "name": "Components",
        "caption": "Components",
        "parent_slug": None,
        "sort_order": 2,
        "is_active": True,
        "show_in_top_menu": True,
    },
    {
        "slug": "storage",
        "name": "Storage",
        "caption": "Storage",
        "parent_slug": "components",
        "sort_order": 0,
        "is_active": True,
        "show_in_top_menu": False,
    },
    {
        "slug": "networking",
        "name": "Networking",
        "caption": "Networking",
        "parent_slug": None,
        "sort_order": 3,
        "is_active": True,
        "show_in_top_menu": False,
    },
]

# Computer-store brands — slugs upserted in init_db.
BRAND_SEED: list[dict] = [
    {"name": "ASUS", "slug": "asus", "sort_order": 0, "logo_url": "https://picsum.photos/seed/brand-asus/64/64"},
    {"name": "Dell", "slug": "dell", "sort_order": 1, "logo_url": "https://picsum.photos/seed/brand-dell/64/64"},
    {"name": "HP", "slug": "hp", "sort_order": 2, "logo_url": "https://picsum.photos/seed/brand-hp/64/64"},
    {"name": "Lenovo", "slug": "lenovo", "sort_order": 3, "logo_url": "https://picsum.photos/seed/brand-lenovo/64/64"},
    {"name": "Apple", "slug": "apple", "sort_order": 4, "logo_url": "https://picsum.photos/seed/brand-apple/64/64"},
    {"name": "Logitech", "slug": "logitech", "sort_order": 5, "logo_url": "https://picsum.photos/seed/brand-logitech/64/64"},
    {"name": "Razer", "slug": "razer", "sort_order": 6, "logo_url": "https://picsum.photos/seed/brand-razer/64/64"},
    {"name": "Samsung", "slug": "samsung", "sort_order": 7, "logo_url": "https://picsum.photos/seed/brand-samsung/64/64"},
    {"name": "LG", "slug": "lg", "sort_order": 8, "logo_url": "https://picsum.photos/seed/brand-lg/64/64"},
    {"name": "Intel", "slug": "intel", "sort_order": 9, "logo_url": "https://picsum.photos/seed/brand-intel/64/64"},
    {"name": "AMD", "slug": "amd", "sort_order": 10, "logo_url": "https://picsum.photos/seed/brand-amd/64/64"},
    {"name": "Corsair", "slug": "corsair", "sort_order": 11, "logo_url": "https://picsum.photos/seed/brand-corsair/64/64"},
    {"name": "Keychron", "slug": "keychron", "sort_order": 12, "logo_url": "https://picsum.photos/seed/brand-keychron/64/64"},
    {"name": "Sony", "slug": "sony", "sort_order": 13, "logo_url": "https://picsum.photos/seed/brand-sony/64/64"},
    {"name": "TP-Link", "slug": "tp-link", "sort_order": 14, "logo_url": "https://picsum.photos/seed/brand-tplink/64/64"},
    {"name": "Canon", "slug": "canon", "sort_order": 15, "logo_url": "https://picsum.photos/seed/brand-canon/64/64"},
    {"name": "Xiaomi", "slug": "xiaomi", "sort_order": 16, "logo_url": "https://picsum.photos/seed/brand-xiaomi/64/64"},
    {"name": "Anker", "slug": "anker", "sort_order": 17, "logo_url": "https://picsum.photos/seed/brand-anker/64/64"},
]

COLLECTION_SEED: list[dict] = [
    {
        "name": "Featured Products",
        "slug": "featured",
        "collection_type": "featured",
        "status": "active",
        "sort_order": 0,
        "product_count": 24,
        "rule_summary": "is_featured = true",
        "hero_image_url": "https://picsum.photos/seed/col-featured/120/80",
        "description": "Homepage hero and campaign slots.",
        "is_system": True,
    },
    {
        "name": "New Arrivals",
        "slug": "new-arrivals",
        "collection_type": "new_arrivals",
        "status": "active",
        "sort_order": 1,
        "product_count": 36,
        "rule_summary": "created_at > NOW() - 30 days",
        "hero_image_url": "https://picsum.photos/seed/col-new/120/80",
        "is_system": True,
    },
    {
        "name": "Best Sellers",
        "slug": "best-sellers",
        "collection_type": "best_sellers",
        "status": "active",
        "sort_order": 2,
        "product_count": 48,
        "rule_summary": "Sales rank from analytics (top 50)",
        "hero_image_url": "https://picsum.photos/seed/col-best/120/80",
        "is_system": True,
    },
    {
        "name": "Trending Now",
        "slug": "trending",
        "collection_type": "trending",
        "status": "active",
        "sort_order": 3,
        "product_count": 20,
        "rule_summary": "View velocity · last 7 days",
        "hero_image_url": "https://picsum.photos/seed/col-trend/120/80",
        "is_system": True,
    },
    {
        "name": "Summer Sale 2026",
        "slug": "summer-sale-2026",
        "collection_type": "custom",
        "status": "active",
        "sort_order": 4,
        "product_count": 18,
        "rule_summary": "Manual product pick list (18 SKUs)",
        "hero_image_url": "https://picsum.photos/seed/col-summer/120/80",
        "description": "Seasonal merchandising set for June–August.",
        "schedule_start": "2026-06-01",
        "schedule_end": "2026-08-31",
    },
    {
        "name": "Electronics Under ৳5,000",
        "slug": "electronics-under-5k",
        "collection_type": "rules",
        "status": "active",
        "sort_order": 5,
        "product_count": 32,
        "rule_summary": "category = Electronics AND price < 5000",
        "hero_image_url": "https://picsum.photos/seed/col-elec/120/80",
    },
    {
        "name": "UrbanWear Picks",
        "slug": "urbanwear-picks",
        "collection_type": "rules",
        "status": "active",
        "sort_order": 6,
        "product_count": 14,
        "rule_summary": "brand = UrbanWear AND status = published",
        "hero_image_url": "https://picsum.photos/seed/col-urban/120/80",
    },
    {
        "name": "Gift Guide",
        "slug": "gift-guide",
        "collection_type": "custom",
        "status": "draft",
        "sort_order": 7,
        "product_count": 0,
        "rule_summary": "Manual product pick list (empty)",
        "hero_image_url": "https://picsum.photos/seed/col-gift/120/80",
    },
    {
        "name": "Clearance",
        "slug": "clearance",
        "collection_type": "dynamic",
        "status": "inactive",
        "sort_order": 8,
        "product_count": 56,
        "rule_summary": "stock < 10 OR compare_at_price > price",
        "hero_image_url": "https://picsum.photos/seed/col-clear/120/80",
    },
    {
        "name": "Ramadan Collection 2025",
        "slug": "ramadan-2025",
        "collection_type": "custom",
        "status": "archived",
        "sort_order": 9,
        "product_count": 22,
        "rule_summary": "Manual product pick list (archived)",
    },
]

FILTER_SEED: list[dict] = [
    {
        "name": "Brand",
        "param_key": "brand",
        "display_type": "multi_select",
        "source": "attribute",
        "attribute_name": "Brand",
        "sort_order": 0,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "All categories",
        "value_count": 12,
        "url_example": "?brand=apple&brand=samsung",
    },
    {
        "name": "Price",
        "param_key": "price",
        "display_type": "range",
        "source": "built_in",
        "attribute_name": "Selling price",
        "sort_order": 1,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "All categories",
        "value_count": 0,
        "url_example": "?price_min=10000&price_max=50000",
        "is_system": True,
    },
    {
        "name": "Color",
        "param_key": "color",
        "display_type": "color",
        "source": "attribute",
        "attribute_name": "Color",
        "sort_order": 2,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "All categories",
        "value_count": 18,
        "url_example": "?color=red&color=black",
    },
    {
        "name": "RAM",
        "param_key": "ram",
        "display_type": "dynamic",
        "source": "attribute",
        "attribute_name": "RAM",
        "sort_order": 3,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "Electronics",
        "value_count": 6,
        "url_example": "?ram=8gb&ram=16gb",
    },
    {
        "name": "Storage",
        "param_key": "storage",
        "display_type": "dynamic",
        "source": "attribute",
        "attribute_name": "Storage",
        "sort_order": 4,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "Electronics",
        "value_count": 8,
        "url_example": "?storage=128gb&storage=256gb",
    },
    {
        "name": "Processor",
        "param_key": "processor",
        "display_type": "dynamic",
        "source": "attribute",
        "attribute_name": "Processor",
        "sort_order": 5,
        "is_active": True,
        "storefront_visible": False,
        "category_scope": "Laptops",
        "value_count": 14,
        "url_example": "?processor=intel-i7",
    },
    {
        "name": "In stock only",
        "param_key": "in_stock",
        "display_type": "boolean",
        "source": "built_in",
        "attribute_name": "Stock status",
        "sort_order": 6,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "All categories",
        "value_count": 0,
        "url_example": "?in_stock=true",
        "is_system": True,
    },
    {
        "name": "On sale",
        "param_key": "on_sale",
        "display_type": "boolean",
        "source": "built_in",
        "attribute_name": "Offer price",
        "sort_order": 7,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "All categories",
        "value_count": 0,
        "url_example": "?on_sale=true",
    },
    {
        "name": "Weight",
        "param_key": "weight",
        "display_type": "range",
        "source": "attribute",
        "attribute_name": "Weight",
        "sort_order": 8,
        "is_active": False,
        "storefront_visible": False,
        "category_scope": "Electronics",
        "value_count": 0,
        "url_example": "?weight_min=0.5&weight_max=2",
    },
    {
        "name": "Screen size",
        "param_key": "screen",
        "display_type": "range",
        "source": "attribute",
        "attribute_name": "Screen Size",
        "sort_order": 9,
        "is_active": True,
        "storefront_visible": True,
        "category_scope": "Phones & Tablets",
        "value_count": 0,
        "url_example": "?screen_min=6&screen_max=6.8",
    },
]

CONFIGURATOR_TEMPLATE_SEED: list[dict] = [
    {
        "profile_slug": "pc-builder",
        "name": "Gaming Starter",
        "slug": "gaming-starter",
        "description": "Mid-range gaming build with RTX 4060",
        "components": [
            {"category_slug": "cpu", "category_name": "Processor", "product_name": "Intel Core i5-14600K", "quantity": 1},
            {"category_slug": "motherboard", "category_name": "Motherboard", "product_name": "ASUS Z790-P", "quantity": 1},
            {"category_slug": "ram", "category_name": "RAM", "product_name": "Corsair 32GB DDR5 5600", "quantity": 1},
            {"category_slug": "gpu", "category_name": "GPU", "product_name": "NVIDIA RTX 4060", "quantity": 1},
        ],
        "is_featured": True,
        "status": "active",
        "use_count": 56,
    },
    {
        "profile_slug": "pc-builder",
        "name": "Office Productivity",
        "slug": "office-productivity",
        "description": "Quiet office workstation without dedicated GPU",
        "components": [
            {"category_slug": "cpu", "category_name": "Processor", "product_name": "Intel Core i3-14100", "quantity": 1},
            {"category_slug": "motherboard", "category_name": "Motherboard", "product_name": "MSI B760M", "quantity": 1},
            {"category_slug": "ram", "category_name": "RAM", "product_name": "Kingston 16GB DDR4", "quantity": 1},
        ],
        "is_featured": False,
        "status": "active",
        "use_count": 34,
    },
    {
        "profile_slug": "pc-builder",
        "name": "Creative Workstation",
        "slug": "creative-workstation",
        "description": "High-end creative workstation",
        "components": [
            {"category_slug": "cpu", "category_name": "Processor", "product_name": "AMD Ryzen 9 7950X", "quantity": 1},
            {"category_slug": "ram", "category_name": "RAM", "product_name": "G.Skill 64GB DDR5", "quantity": 1},
            {"category_slug": "gpu", "category_name": "GPU", "product_name": "NVIDIA RTX 4070 Ti", "quantity": 1},
        ],
        "is_featured": True,
        "status": "draft",
        "use_count": 8,
    },
]

CONFIGURATOR_BUILD_SEED: list[dict] = [
    {
        "profile_slug": "pc-builder",
        "name": "Rahim's Gaming PC",
        "build_code": "PC-2026-0142",
        "customer_name": "Rahim Ahmed",
        "components": [
            {"category_slug": "cpu", "category_name": "CPU", "product_name": "Intel i5-14600K", "quantity": 1},
            {"category_slug": "gpu", "category_name": "GPU", "product_name": "RTX 4060", "quantity": 1},
        ],
        "total_price": 98500,
        "compatibility_status": "compatible",
        "status": "saved",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Office Build #7",
        "build_code": "PC-2026-0138",
        "customer_name": "TechGadgets BD",
        "components": [
            {"category_slug": "cpu", "category_name": "CPU", "product_name": "Intel i3-14100", "quantity": 1},
        ],
        "total_price": 42000,
        "compatibility_status": "warning",
        "status": "ordered",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Socket mismatch test",
        "build_code": "PC-2026-0135",
        "user_name": "Guest",
        "components": [
            {"category_slug": "cpu", "category_name": "CPU", "product_name": "AMD Ryzen 7", "quantity": 1},
            {"category_slug": "motherboard", "category_name": "Motherboard", "product_name": "Intel Z790", "quantity": 1},
        ],
        "total_price": 0,
        "compatibility_status": "incompatible",
        "status": "abandoned",
    },
    {
        "profile_slug": "laptop-builder",
        "name": "Student Laptop",
        "build_code": "LP-2026-0008",
        "customer_name": "Nadia Islam",
        "components": [
            {"category_slug": "chassis", "category_name": "Chassis", "product_name": '14" Ultrabook Shell', "quantity": 1},
        ],
        "total_price": 55000,
        "compatibility_status": "compatible",
        "status": "draft",
    },
]

CONFIGURATOR_CATEGORY_SEED: list[dict] = [
    {
        "profile_slug": "pc-builder",
        "name": "Processor (CPU)",
        "slug": "cpu",
        "description": "Intel and AMD processors",
        "sort_order": 1,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 48,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Motherboard",
        "slug": "motherboard",
        "sort_order": 2,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 36,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Memory (RAM)",
        "slug": "ram",
        "sort_order": 3,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 52,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Graphics Card",
        "slug": "gpu",
        "sort_order": 4,
        "is_required": False,
        "selection_mode": "single",
        "product_count": 28,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Storage",
        "slug": "storage",
        "sort_order": 5,
        "is_required": True,
        "selection_mode": "multiple",
        "product_count": 64,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Power Supply",
        "slug": "psu",
        "sort_order": 6,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 22,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "Case",
        "slug": "case",
        "sort_order": 7,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 18,
        "status": "active",
    },
    {
        "profile_slug": "pc-builder",
        "name": "CPU Cooler",
        "slug": "cooler",
        "sort_order": 8,
        "is_required": False,
        "selection_mode": "single",
        "product_count": 24,
        "status": "draft",
    },
    {
        "profile_slug": "laptop-builder",
        "name": "Chassis",
        "slug": "chassis",
        "sort_order": 1,
        "is_required": True,
        "selection_mode": "single",
        "product_count": 8,
        "status": "active",
    },
]

CONFIGURATOR_PROFILE_SEED: list[dict] = [
    {
        "name": "PC Builder",
        "slug": "pc-builder",
        "profile_type": "pc_builder",
        "description": "Desktop PC configurator — CPU, motherboard, RAM, GPU, storage, PSU, case.",
        "is_default": True,
        "status": "active",
        "category_count": 8,
        "rule_count": 4,
        "template_count": 3,
        "build_count": 142,
    },
    {
        "name": "Laptop Builder",
        "slug": "laptop-builder",
        "profile_type": "laptop_builder",
        "description": "Custom laptop configurator with chassis, display, and upgrade slots.",
        "is_default": False,
        "status": "active",
        "category_count": 6,
        "rule_count": 2,
        "template_count": 2,
        "build_count": 38,
    },
    {
        "name": "CCTV Builder",
        "slug": "cctv-builder",
        "profile_type": "cctv_builder",
        "description": "Surveillance kit builder — cameras, NVR, cables, storage.",
        "is_default": False,
        "status": "draft",
        "category_count": 5,
        "rule_count": 1,
        "template_count": 1,
        "build_count": 12,
    },
]

ATTRIBUTE_PROFILE_SEED: list[dict] = [
    {
        "code": "laptop",
        "name": "Laptop",
        "description": "Notebook and laptop specification template.",
        "sort_order": 0,
        "is_active": True,
        "icon_url": "https://picsum.photos/seed/prof-laptop/64/64",
        "category_labels": ["Computers", "Laptops"],
        "groups": [
            {
                "code": "processor",
                "name": "Processor",
                "sort_order": 0,
                "attributes": [
                    {
                        "code": "processor_brand",
                        "name": "Processor Brand",
                        "field_type": "dropdown",
                        "is_filterable": True,
                        "predefined_values": ["Intel", "AMD", "Apple"],
                    },
                    {
                        "code": "ram",
                        "name": "RAM",
                        "field_type": "dropdown",
                        "is_filterable": True,
                        "unit": "GB",
                        "predefined_values": ["8 GB", "16 GB", "32 GB"],
                    },
                ],
            },
            {
                "code": "display",
                "name": "Display",
                "sort_order": 1,
                "attributes": [
                    {
                        "code": "display_size",
                        "name": "Display Size",
                        "field_type": "dropdown",
                        "is_filterable": True,
                        "unit": "inch",
                        "predefined_values": ["14\"", "15.6\"", "16\""],
                    },
                ],
            },
        ],
    },
    {
        "code": "mobile_phone",
        "name": "Mobile Phone",
        "description": "Smartphone specification template.",
        "sort_order": 1,
        "is_active": True,
        "icon_url": "https://picsum.photos/seed/prof-mobile/64/64",
        "category_labels": ["Electronics", "Phones"],
        "groups": [
            {
                "code": "display",
                "name": "Display",
                "sort_order": 0,
                "attributes": [
                    {
                        "code": "screen_size",
                        "name": "Screen Size",
                        "field_type": "dropdown",
                        "is_filterable": True,
                        "predefined_values": ["6.1\"", "6.4\"", "6.7\""],
                    },
                ],
            },
        ],
    },
    {
        "code": "monitor",
        "name": "Monitor",
        "sort_order": 2,
        "is_active": True,
        "category_labels": ["Monitors"],
        "groups": [],
    },
    {
        "code": "camera",
        "name": "Camera",
        "sort_order": 3,
        "is_active": True,
        "category_labels": ["Electronics", "Cameras"],
        "groups": [],
    },
]

MEDIA_SEED: list[dict] = []
_UPLOADERS = ["Admin", "Sadia Rahman", "Rahim Hossain", "Karim Ali"]

for i in range(24):
    is_video = i % 5 == 0
    is_doc = i % 7 == 0 and not is_video
    folder = "Products" if i % 3 == 0 else "Banners" if i % 3 == 1 else "Blog"
    is_banner = not is_doc and not is_video and folder == "Banners"
    base_name = (
        f"document-{i + 1}.pdf"
        if is_doc
        else f"clip-{i + 1}.mp4"
        if is_video
        else f"banner-{i + 1}.jpg"
        if is_banner
        else f"asset-{i + 1}.jpg"
    )
    title = base_name.rsplit(".", 1)[0].replace("-", " ").replace("_", " ")
    media_type = "document" if is_doc else "video" if is_video else "image"
    url = (
        "https://placehold.co/480x480/f5f5f5/666?text=PDF"
        if is_doc
        else f"https://picsum.photos/seed/mediavid{i}/480/480"
        if is_video
        else f"https://picsum.photos/seed/banner{i}/800/200"
        if is_banner
        else f"https://picsum.photos/seed/media{i}/480/480"
    )
    mime = (
        "application/pdf"
        if is_doc
        else "video/mp4"
        if is_video
        else "image/jpeg"
    )
    MEDIA_SEED.append(
        {
            "name": base_name,
            "title": title,
            "folder": "Documents" if is_doc else folder,
            "url": url,
            "media_type": media_type,
            "mime_type": mime,
            "size_kb": 120 + i * 18,
            "alt": title,
            "uploaded_by": _UPLOADERS[i % len(_UPLOADERS)],
            "title_linked_to_name": True,
            "alt_linked_to_name": True,
        },
    )

WAREHOUSE_SEED: list[dict] = [
    {
        "id": "wh_dhaka",
        "code": "DHK-HQ",
        "name": "Dhaka HQ",
        "type": "Main warehouse",
        "address": "Gulshan-2, Dhaka",
        "locations_count": 24,
        "is_active": True,
        "sort_order": 0,
    },
    {
        "id": "wh_ctg",
        "code": "CTG-01",
        "name": "Chittagong",
        "type": "Regional",
        "address": "Agrabad, Chittagong",
        "locations_count": 12,
        "is_active": True,
        "sort_order": 1,
    },
    {
        "id": "wh_fc",
        "code": "ONL-FC",
        "name": "Online Fulfillment Center",
        "type": "Ecommerce FC",
        "address": "Savar EPZ",
        "locations_count": 18,
        "is_active": True,
        "sort_order": 2,
    },
]
