"""Seed payloads for commerce_suppliers — mirrors admin mock suppliers."""

from __future__ import annotations

from decimal import Decimal

SUPPLIER_SEED: list[dict] = [
    {
        "id": "sup_001",
        "vendor_code": "VND-TECH",
        "name": "TechPro Distributors Ltd",
        "email": "orders@techpro.bd",
        "phone": "+880 1711-000001",
        "payment_terms": "Net 30",
        "lead_time_days": 7,
        "rating": Decimal("4.60"),
        "open_pos": 2,
        "spend_ytd": Decimal("4200000.00"),
        "status": "preferred",
        "country": "Bangladesh",
        "tax_id": "BIN-123456789",
        "website": "https://techpro.bd",
        "currency": "BDT",
        "min_order_value": Decimal("50000.00"),
        "incoterms": "FOB Dhaka",
        "buyer_name": "Rahim Uddin",
        "rfq_count": 3,
        "receipt_count": 12,
        "has_stock_feed": True,
        "total_pos": 4,
        "contacts": [
            {
                "id": "c1",
                "name": "Nasir Hossain",
                "role": "Sales Manager",
                "email": "nasir@techpro.bd",
                "phone": "+880 1711-100001",
                "isPrimary": True,
            },
            {
                "id": "c2",
                "name": "Farhana Akter",
                "role": "Accounts",
                "email": "accounts@techpro.bd",
                "phone": "+880 1711-100002",
                "isPrimary": False,
            },
        ],
        "addresses": [
            {
                "id": "a1",
                "label": "Head office",
                "type": "billing",
                "line1": "12 Tejgaon Industrial Area",
                "city": "Dhaka",
                "country": "Bangladesh",
            },
            {
                "id": "a2",
                "label": "Warehouse",
                "type": "warehouse",
                "line1": "Plot 45, Tongi EPZ",
                "city": "Gazipur",
                "country": "Bangladesh",
            },
        ],
        "contracts": [
            {
                "id": "ct1",
                "contractNumber": "CTR-2026-004",
                "title": "Electronics annual supply",
                "validFrom": "2026-01-01",
                "validTo": "2026-12-31",
                "status": "active",
                "value": 6000000,
            },
        ],
        "bills": [
            {
                "id": "b1",
                "billNumber": "VB-2026-089",
                "amount": 620000,
                "status": "paid",
                "dueAt": "2026-06-10",
            },
            {
                "id": "b2",
                "billNumber": "VB-2026-102",
                "amount": 420000,
                "status": "matched",
                "dueAt": "2026-07-05",
            },
        ],
        "performance": {
            "onTimeDeliveryPct": 94,
            "qualityRejectRatePct": 1.2,
            "priceVariancePct": -2.1,
            "avgLeadTimeDays": 6,
        },
        "timeline": [
            {
                "id": "t1",
                "type": "po",
                "title": "PO-2026-0142 sent",
                "description": "5 line items · ৳840,000",
                "at": "2026-06-14T10:30:00",
            },
            {
                "id": "t2",
                "type": "receipt",
                "title": "Goods received — PO-2026-0138",
                "description": "8 items received at Main Warehouse",
                "at": "2026-05-28T14:00:00",
            },
        ],
    },
    {
        "id": "sup_002",
        "vendor_code": "VND-FASH",
        "name": "UrbanWear Manufacturing",
        "email": "supply@urbanwear.com",
        "phone": "+880 1711-000002",
        "payment_terms": "Net 45",
        "lead_time_days": 14,
        "rating": Decimal("4.20"),
        "open_pos": 1,
        "spend_ytd": Decimal("3100000.00"),
        "status": "active",
        "country": "Bangladesh",
        "tax_id": "BIN-987654321",
        "website": "https://urbanwear.com",
        "currency": "BDT",
        "min_order_value": Decimal("25000.00"),
        "incoterms": "EXW",
        "buyer_name": "Sadia Khan",
        "rfq_count": 1,
        "receipt_count": 8,
        "has_stock_feed": False,
        "total_pos": 3,
        "contacts": [
            {
                "id": "c1",
                "name": "Imran Chowdhury",
                "role": "Production Head",
                "email": "imran@urbanwear.com",
                "phone": "+880 1711-200001",
                "isPrimary": True,
            },
        ],
        "addresses": [
            {
                "id": "a1",
                "label": "Factory",
                "type": "shipping",
                "line1": "Ashulia Industrial Park",
                "city": "Savar",
                "country": "Bangladesh",
            },
        ],
        "bills": [
            {
                "id": "b1",
                "billNumber": "VB-2026-076",
                "amount": 445000,
                "status": "paid",
                "dueAt": "2026-05-20",
            },
        ],
        "performance": {
            "onTimeDeliveryPct": 88,
            "qualityRejectRatePct": 3.5,
            "priceVariancePct": 1.8,
            "avgLeadTimeDays": 13,
        },
        "timeline": [
            {
                "id": "t1",
                "type": "po",
                "title": "PO-2026-0135 received",
                "description": "6 line items fully received",
                "at": "2026-05-10T11:00:00",
            },
        ],
    },
    {
        "id": "sup_003",
        "vendor_code": "VND-GLOW",
        "name": "GlowUp Beauty Imports",
        "email": "procurement@glowup.bd",
        "phone": "+880 1711-000003",
        "payment_terms": "Net 30",
        "lead_time_days": 10,
        "rating": Decimal("4.00"),
        "open_pos": 1,
        "spend_ytd": Decimal("1860000.00"),
        "status": "active",
        "country": "Bangladesh",
        "tax_id": "BIN-456789123",
        "currency": "BDT",
        "min_order_value": Decimal("15000.00"),
        "incoterms": "CIF Chittagong",
        "buyer_name": "Rahim Uddin",
        "rfq_count": 2,
        "receipt_count": 5,
        "has_stock_feed": False,
        "total_pos": 2,
        "contacts": [
            {
                "id": "c1",
                "name": "Mehjabin Islam",
                "role": "Procurement",
                "email": "mehjabin@glowup.bd",
                "phone": "+880 1711-300001",
                "isPrimary": True,
            },
        ],
        "performance": {
            "onTimeDeliveryPct": 91,
            "qualityRejectRatePct": 2.0,
            "priceVariancePct": 0.5,
            "avgLeadTimeDays": 9,
        },
        "timeline": [
            {
                "id": "t1",
                "type": "po",
                "title": "PO-2026-0140 drafted",
                "description": "3 beauty SKUs · ৳186,000",
                "at": "2026-06-15T08:00:00",
            },
        ],
    },
    {
        "id": "sup_004",
        "vendor_code": "VND-CN-ELC",
        "name": "Shenzhen Electronics Co.",
        "email": "export@szelec.cn",
        "phone": "+86 755-0000",
        "payment_terms": "50% advance",
        "lead_time_days": 28,
        "rating": Decimal("3.80"),
        "open_pos": 3,
        "spend_ytd": Decimal("5400000.00"),
        "status": "preferred",
        "country": "China",
        "tax_id": "91440300MA5XXXX",
        "website": "https://szelec.cn",
        "currency": "USD",
        "min_order_value": Decimal("5000.00"),
        "incoterms": "FOB Shenzhen",
        "buyer_name": "Karim Ahmed",
        "rfq_count": 5,
        "receipt_count": 18,
        "has_stock_feed": True,
        "total_pos": 6,
        "contacts": [
            {
                "id": "c1",
                "name": "Li Wei",
                "role": "Export Manager",
                "email": "liwei@szelec.cn",
                "phone": "+86 755-8888",
                "isPrimary": True,
            },
        ],
        "performance": {
            "onTimeDeliveryPct": 82,
            "qualityRejectRatePct": 4.8,
            "priceVariancePct": -5.2,
            "avgLeadTimeDays": 26,
        },
        "timeline": [
            {
                "id": "t1",
                "type": "rfq",
                "title": "RFQ-2026-008 response submitted",
                "description": "Quoted 4 SKUs with 25-day lead time",
                "at": "2026-06-12T16:00:00",
            },
        ],
    },
    {
        "id": "sup_005",
        "vendor_code": "VND-HOME",
        "name": "HomeNest Wholesale",
        "email": "b2b@homenest.bd",
        "phone": "+880 1711-000005",
        "payment_terms": "COD",
        "lead_time_days": 5,
        "rating": Decimal("3.20"),
        "open_pos": 0,
        "spend_ytd": Decimal("420000.00"),
        "status": "blocked",
        "country": "Bangladesh",
        "currency": "BDT",
        "min_order_value": Decimal("10000.00"),
        "buyer_name": "Sadia Khan",
        "rfq_count": 0,
        "receipt_count": 2,
        "has_stock_feed": False,
        "total_pos": 1,
        "contacts": [
            {
                "id": "c1",
                "name": "Rafiqul Alam",
                "role": "Owner",
                "email": "rafiq@homenest.bd",
                "phone": "+880 1711-500001",
                "isPrimary": True,
            },
        ],
        "performance": {
            "onTimeDeliveryPct": 65,
            "qualityRejectRatePct": 8.2,
            "priceVariancePct": 6.4,
            "avgLeadTimeDays": 8,
        },
        "timeline": [
            {
                "id": "t1",
                "type": "note",
                "title": "Vendor blocked",
                "description": "Repeated late deliveries and quality issues",
                "at": "2026-06-01T12:00:00",
            },
        ],
    },
]
